### ISSUE TITLE
routing issue after version 0.8.0

### ISSUE THREAD

**Issue by mdorson98221** [framework7io/framework7-vue#107]
Ive been using 0.7.8 a while and when I upgrade to 0.8.0 and above, my links do not work nor does my programmatic routing.

This fails now, and it loads with 0.7.8:
`<f7-link class="button button-fill" href="/search/">Get Started</f7-link>`
It basically does nothing with no errors.

Also this no longer works in my code:
self.$router.load({ url: 'nearby/', reload: true });
It basically does nothing with no errors.

But I am able to get this to work:
self.$f7.views[0].router.load({ url: 'nearby/', reload: true });

Im sure there is something I am missing as no one else seems to be having the issue. Im hoping someone can pinpoint me in the right direction. Thanks!

**Comment by bencompton** [comment]
```javascript
<f7-link class="button button-fill" href="/search/">Get Started</f7-link>
```

There are plenty of examples of this syntax in the kitchen sink that work perfectly fine. We would need to see more details about how your routes are configured, or anything other than the standard configuration (like the kitchen sink) that you're doing.

```javascript
self.$router.load({ url: 'nearby/', reload: true });
```

[The F7 router](https://github.com/nolimits4web/Framework7/blob/6b8a3033b150fea0b4967831488b0bea7f669fc7/src/js/framework7/router.js#L648) requires the view as the first parameter and the options as the second parameter, and the view isn't optional, so I'm not exactly sure why that would have ever worked for you. It makes sense that invoking it directly from a view would work, though.

**Comment by mdorson98221** [comment]
Thanks for your response. Here is my code to initialize:
`vueapp=new Vue({
            el: '#app',
           
            render: h => h(Home),
            //render: function(h){
            //    return Home;
            //},
            // Framework7 Parameters
            framework7: {
                root: '#app', //Should be same as app el
                animateNavBackIcon: true,
                routes: Routes,
                modalTitle: 'TipJar',
                swipeBackPage: true,
                material:true,
                materialPageLoadDelay: 50,
                swipePanelOnlyClose: true,
                modalActionsTemplate:'<div class="actions-modal tj-action">{{#each this}}<div class="actions-modal-group">{{#each this}}{{#if label}}<span class="actions-modal-label">{{text}}</span>' +
                    '{{else}}<div class="actions-modal-button {{#if color}}color-{{color}}{{/if}} {{#if bold}}actions-modal-button-bold{{/if}}">{{text}}</div>{{/if}}' +
                    '{{/each}} </div>{{/each}} </div>'
            }, 
            data: rootData
 });

Im wondering if its using the default "Render" to load the home page the issue of why my links no longer work with 0.8.0? The routes are in a separate JS file that I took from the initial kitchen sink example. `
partial example:
`import SearchPage from 'pages/search.vue';
export default [
{
          path: '/search/',
          component: SearchPage
      }
];
`

**Comment by bencompton** [comment]
So are you using 0.8.0? You might consider trying 0.8.5 if you haven't already.

I wouldn't expect that your inline render would be problematic, presuming that "Home" doesn't just contain a Page component and instead contains your main view with a pages component, etc. For example, in the Webpack starter template, it has a [template for rendering the App component](https://github.com/nolimits4web/Framework7-Vue-Webpack-Template/blob/master/src/main.js#L33), which would end up compiling to be a render method similar to yours.

**Comment by nolimits4web** [comment]
Yes, check the 0.8.5 There was an issue with $router pointing to different router in 0.8.0

**Comment by mdorson98221** [comment]
Hi..Yea Ive been using the latest 0.8.5. My Home.vue has the following below and after it is rendered my links do not work. This is only for the first home page..Once I use the @click function to force a reload to another page, then all my links are working for f7. It seems the navigation doesnt work for first render using this method. My goal was to have only a `<div id="app"></div>` in my index page and nothing else.

Home.vue:

` <div id="app">
    <f7-statusbar></f7-statusbar>
    <div class="panel-overlay"></div>
    <f7-views>
        <f7-view main url="/">
            <f7-pages navbar-fixed toolbar-fixed>
                <f7-page name="main" no-navbar no-toolbar no-swipeback>
                    <f7-block class="center">
                        <img v-if="logo" :src="logo" />
                    </f7-block>
                    <f7-link class="button button-fill" href="/search/" @click="search">Get Started</f7-link>
                </f7-page>
            </f7-pages>
        </f7-view>
    </f7-views>
   

   </div>`

**Comment by mdorson98221** [comment]
But obviously I have a workaround so Im ok now. Thanks for your help.

**Comment by bencompton** [comment]
@mdorson98221 - not sure I follow what workaround you are referencing. Did you mean that you initially had just `<div id="app"></div>` in your home.vue and it didn't work, so then you added the additional content with the view and pages components in your post above and that got it working?

**Comment by mdorson98221** [comment]
Sorry for the confusion. The code I posted is my original code without any changes. My workaround at the moment is using the @click event on my home vue to change the page from Home to another page. The link wont work.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
