### ISSUE TITLE
Back links make data disappear, invalid prop error on regular links

### ISSUE THREAD

**Issue by chasebank** [framework7io/framework7-vue#116]
I have one version of my app, using a [webpack template](https://github.com/valnub/vue-framework7-webpack-template) and F7 Vue 0.7.7  In that one, everything works fine. No errors, I can navigate all over the place, and add data, nothing breaks.

Now I've ported everything over to the [Cordova Webpack template](https://github.com/centrual/cordova-template-framework7-vue-webpack) which is running F7 Vue 0.8.5, and I'm serving with PhoneGap.

Now I'm experiencing trouble navigating backward through the routes, especially if there's any changes in data. The back button takes me to blank pages.

Another scenario, is I have a form to add an item, using an @click method. When the form is submitted, I load the dynamic route of that new item. I'm doing that with `this.$f7['mainView'].loadPage('/product/' + productKey + '/');` in the method.

And that dynamic route is set up like:
```
{
    path: '/product/:product/',
    component: require('./assets/vue/pages/product.vue')
}
```

So, there's sort of a 'products' page, and then you can click an individual product which leads to the above route. I can view existing product data with no problem, and when adding new products, that .loadPage appears to work perfect as well. You add a new product, and are automatically forwarded to it. But then when I click a back link, rather than take me back to products, it tries loading the very same new product page, with broken data.

Inspecting using the Vue dev tools, I noticed the path of the route object doesn't change when hitting back. Is there a way to force it to reload the new path?

```
$route:Object
  params:Object
  path:"/product/6/"
```

Here's how I'm doing back links `<f7-link back></f7-link>`  I also tried `<f7-link back reload></f7-link>` but that didn't appear to have any effect.

This may also be caused by my links, which seem to work fine, but I'm getting a new console error `Invalid prop: type check failed for prop "href". Expected String, got RegExp. 
(found in <F7Link>)`  And an example link is `<f7-link :href='"/product/" + product.$loki + "/"'>{{ product.title }}</f7-link>`. I don't get that error on the older version that doesn't have this back link problem.

Any ideas? Thanks!

**Comment by nolimits4web** [comment]
Well, that is definitely something weird. Can you provide some kind of demo so i can check it live?

**Comment by chasebank** [comment]
Sure thing! Thanks for taking the time to look at this. I started with a fresh template (the Cordova F7 Vue), and rebuilt a simple test. I'm not seeing the href prop error, but do still have the data/route issue.

I set up a repo with the demo https://github.com/chasebank/Framework7-Vue-PhoneGap 

There's a list of items for data, each with a title, category, and id. And we have 3 pages:

- **The main Vue instance** - a computed list that returns the categories.
- **Category** - dynamic route with a computed filtered list returning items with *this* category.
- **Item** - dynamic route for an item.

First, navigate to a category and check the route object.

```
$route:Object
params:Object
  category:"category 1"
```

Looks good so far... Now navigate to an item.

```
$route:Object
params:Object
  category:"78fa19d0"
  itemId:"78fa19d0"
```
Now we see both the category and item param, even though the item route should only have one param, but both show the same. itemID is correct, category clearly is not. You can navigate back to the category, and it still works for some reason.

Navigate back to the main categories page. You can add a new item and category from here. On submit, you're forwarded to the new item. The back button takes you back to categories. Everything's working so far.

Now navigate to a category page. In the navbar, I'm identifying the category with `{{ $route.params.category }}`. When adding an item from here, I'm auto-populating the new item's category field with *this* category using that route param. I don't think this has any relation to the problem, but here's that method:
```
createItem() {
        var newItemTitle = this.newItemTitle.trim(),
          newItemCategory = this.$route.params.category,
          uid = guid();
        
        store.items.push({
          title: newItemTitle,
          category: newItemCategory,
          id: uid
        })
        
        this.newItemTitle = '';
        
        this.$f7['mainView'].loadPage('/item/' + uid + '/');
      }
```
When you submit the new item, the first thing I notice is that as the new item component is sliding into view, you can see the title in the navbar for the category **immediately** switch to the route param of the item.

Once you're on the new item page, everything appears to look fine, until you navigate back to the category, and you still see the wrong param in navbar, and the rest of the data is broken because it was filtered for, using that param.
```
computed: {
      categoryItems() {
        return this.items
          .filter(item => (item.category == this.$route.params.category))
      },
    }
```
Hope all that makes sense... It's quite possible I'm doing something entirely wrong, or handling state incorrectly. I know F7's router is similar to Vue but different, but those differences aren't entirely obvious.

Thanks for the help!

**Comment by chasebank** [comment]
Hi @nolimits4web have you had a chance to take a look at this yet?

**Comment by nolimits4web** [comment]
@chasebank yes, see the error and problem. Needs sometime to make a right fix for it

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
