### ISSUE TITLE
npm 0.9.0 no kitchen folder. Nested tab content after back button is empty

### ISSUE THREAD

**Issue by Matheo13** [framework7io/framework7-vue#134]
Hi,

It seems there is an issue on the npm package for (framework7-vue@0.9.0) release,
I don't have a kitchen folder (with npm again).
I tried by the way to update my app from 0.8.5 but my app seems borken with this new release if it's the good one.
EDIT: `<f7-tab route-tab-id="obs" /> ` became `<f7-tab id="obs" />`

Otherwise, the active prop seems not to work on nested tabs, certainly normal if it's a nested route and I know you don't plan to add it on pushState for now. Could you explain me what is the point of nested tab if you don't use push state? Why not just use the classic tabs? For reload pages or split tab content by component? Thanks.

I have this related issue, I'll try to be clear. When I click on a list-item-link which is inside a nested-tab (among other nested tabs and inside a page), It well redirects to an other page. This new page where I display others nested tab. So far it works well but when I use the back-link to come back to the first/previous page, It well redirects to the previous page but no content tab is displayed, I have to click again on the tab button to display his content/component.
I tried `back-link-url="/route-to-the-prev-page/"` but it doesn't work and display again the current page.

I saw small mistakes on the documentation, is it versionned? 
By the way, I don't think that you plan to do it right know, but I didn't found an f7-vue bhv to use list-item-link with the checked property, it always redirect, it there a default way to define an "off link area" in order to use the checked prop or others?
Thank you.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
