### ISSUE TITLE
Inline modals still buggy

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-vue#138]
Thank you Vladimir, #137 fix improved the situation, but I have still two issues:

- [ ] Action sheet not visible after openModal
- [ ] Login screen visible on load at the end of the page

**Comment by joseph2002** [comment]
add `<div class="modal-overlay"></div>` to root element:
it seems f7-action inside f7-page component can reuse this one
```
    <div id="app">
        <f7-views tabs tabbar-labels-fixed>
            ...
        </f7-views>
        <div class="modal-overlay"></div>
    </div>
```

**Comment by scriptPilot** [comment]
@joseph2002, @nolimits4web  - Unfortunately that does not fix the issues, mentioned above :-(

**Comment by scriptPilot** [comment]
@nolimits4web - Tested with the code below, there is the following behavior:

- I open the modal with `f7.openModal(...)`
- The overlay is shown
- The actions block is still "display: none"
- The Vue components emits onOpen

As the opening should be possible by f7.openModal() as well, not only by updating the prop, what is the best way to fix that?
 
```
<f7-page>
   <f7-actions id="demoActions">
      <f7-actions-group>
        <f7-actions-label>Whatever you want</f7-actions-label>
        <f7-actions-button @click="$f7.alert('Clicked first button')">Button 1</f7-actions-button>
        <f7-actions-button @click="$f7.alert('Clicked second button')">Button 2</f7-actions-button>
      </f7-actions-group>
      <f7-actions-group>
        <f7-actions-button color="red" bold>Cancel</f7-actions-button>
      </f7-actions-group>
    </f7-actions>
    <f7-block>
      <f7-col><f7-button raised @click="$f7.openModal('#demoActions')">Action sheet</f7-button></f7-col>
   </f7-block>
</f7-page>
```

**Comment by scriptPilot** [comment]
PS: A quick and dirty solution is to modify framework7-vue.js / Actions block:

```
onOpen: function (event) {
   this.opened = true
   this.$emit('actions:open', event)
},
onClose: function (event) {
   this.opened = false
   this.$emit('actions:close', event);
}
```

But with the following warning from Vue.js:

![bildschirmfoto 2017-05-12 um 10 38 07](https://cloud.githubusercontent.com/assets/19615586/25990260/57df35ec-36ff-11e7-8d8f-6fcf1c37a24f.png)

**Comment by scriptPilot** [comment]
Regarding the login screen, which is visible on page load, my workaround is:

`window.Dom7(e.target).find('.login-screen.modal-out').hide()`

**Comment by joseph2002** [comment]
add <div class="modal-overlay"></div> to the root solved my issue about f7-actions inside f7-page, could you try it without applying #137 ?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by Robula** [comment]
This is issue is still relevant in v1.

**Comment by Robula** [comment]
@scriptPilot @nolimits4web Do you have a solution to this please?
