### ISSUE TITLE
Searchbar w/ Virtual List (undefined error)

### ISSUE THREAD

**Issue by BHunter2889** [framework7io/framework7-vue#162]
I've created a searchbar to be used as the center part of a Navbar with what should be a drop-down virtual list on search the way I understand things. I've followed the F7 + Vue docs example of using a Virtual List with searchbar and I'm getting the error that something is undefined. Upon further inspection, this appears to be the Virtual List ('#search-list') as the last item in the stack reads `TypeError: Cannot read property 'offsetHeight' of undefined at g.r.setListSize (framework7.min.js:18)`
So, this makes sense, given that the example shows using a Vue template with a component script, but there are multiple root elements in that example, So I combined the component to contain the whole navbar,and that led me to the above error. I guess I'm just at a loss at this point to even describe what I think could be wrong because I've been at this all day, So I'll post my template and component code:
```
<template id="f7navbar">
  <f7-navbar>
    <f7-nav-left>
      <f7-link><f7-icon material="list"></f7-icon></f7-link>
    </f7-nav-left>
    <f7-nav-center sliding>
      <f7-searchbar
        cancel-link="Cancel"
        data-search-list="#search-list"
        placeholder="Find By Destination..."
        :init="true"
        :clear-button="true"
        >
      </f7-searchbar>

      <!-- This block will become visible when there is nothing found -->
      <f7-list class="searchbar-not-found">
        <f7-list-item title="Nothing found"></f7-list-item>
      </f7-list>

      <!-- Search through this list -->
      <f7-list
        id="search-list"
        class="searchbar-found"
        virtual
        :virtual-items="items"
        :virtual-height="48"
        :virtual-search-all="searchAll"
        :virtual-init="true"
        >
        <!-- Templte 7 Virtual List Item Template -->
        <t7-template>
          <f7-list-item :title="'{{title}}'" :subtitle="'{{subtitle}}' "></f7-list-item>
        </t7-template>
      </f7-list>
    </f7-nav-center>
    <f7-nav-right>
      <f7-link><f7-icon material="map"></f7-icon></f7-link>
    </f7-nav-right>
    
  </f7-navbar>

</template>
```
```
  Vue.component('f7navbar', {
    template: '#f7navbar',
    data: function(){
      var items = [];
      for(var i = 1, len=destinations.length; i<len; i++){
        items.push({
          title: destinations[i]._$data.name,
          subtitle: destinations[i]._$data.id
        })
      }
      console.log(items);
      return {items: items}
    },

    mounted: function(){
      console.log("Search Bar MOUNTED");
    },

    methods: {
        // Function to proceed search results
        searchAll: function (query) {
          console.log(query);
          var self = this;
          var found = [];
          for (var i = 0; i < self.items.length; i++) {
              if (self.items[i].title.indexOf(query) >= 0 || query.trim() === '') found.push(i);
          }
          console.log(found);
          return found;
        }
      }
  });
```
For the record, it does successfully log the `items` list in the console as expected.
Also, I tried using `search-list` as a param instead of `data-search-list` but the former didn't even register as a param in the DOM, but the latter does. 
Any help is greatly appreciated. Thanks!

**Comment by BHunter2889** [comment]
Just in case anyone stumbles upon this having a similar issue, I came up with a work-around:
1) First off, I never did get this working… I ended up scrapping templates AND components, and then just included the f7 instances of the searchbar and virtualList(s) in the root Vue instance.
2) I then used v-model to bind the value of query to data, which surprisingly worked despite the "search" event never being triggered on searchbar in any sort of app configuration I tried.
3) So then, I used a Vue watcher on query and the .f7Searchbar instance (for active state) to toggle booleans with v-show for the search-list and for the not-found list.
4) I then used the same watcher on query to trigger the sequence of onSearch, searchAll, and .f7VirtualList instance .filterItems() methods.
5) Then, for whatever reason, the "@click“ or ”v-on:click" listener did not work (trigger) on the search-list items, but vanillaJS "onclick" did, so I used that to route the event to the vm.onSelected method I created.
Lessons: as nice as the Vi rual List Vue component is, the logic I had to implement to get around this issue made it little worth the trouble and could just as easily be implemented with an plain Vue <li v-for"item in items"> call for list rendering, which would also enable better functionality for Vue list transitions like this or this, which I was not able to implement due to the templating required for Virtual List. The one advantage to Virtual List in this scenario is the caching of rendered list-Items. I hope this helps someone out and saves them some trouble haha!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by MuscledGeek** [comment]
Got same error, solve it by making a <div class='page-content'>  the parent of the virtual list.
