### ISSUE TITLE
Route params added for non-matching routes

### ISSUE THREAD

**Issue by bencompton** [framework7io/framework7-vue#167]
When two different routes have a parameter in the same position, like `hello/:helloId` and `test/:testId`, params for both routes will appear in the route params. For example, the url `hello/123` will end up with params that look like this:

`javascript
{
  helloId: 123,
  testId: 123
}
`

The reason this occurs is because the `findMatchingRoute` function does not make sure that a particular route matches the URL before adding its parameters to the result. Perhaps [this line](https://github.com/nolimits4web/Framework7-Vue/blob/master/src/utils/router.js#L170) should be deleted and there should be another for loop [here](https://github.com/nolimits4web/Framework7-Vue/blob/master/src/utils/router.js#L175) that adds the params after it has been determined that a route matches the URL?

```javascript

if (matchedParts === urlParts.length) {
    for (var k = 0; k < parsedRoute.length; k++) {
        if (typeof parsedRoute[k] === 'object') {
            params[parsedRoute[k].name] = urlParts[k];
        }
    }

    matchingRoute = {
        query: query,
        hash: hash,
        params: params,
        url: url,
        path: path,
        route: route
    };
}
```

I think that should fix it, but I know the routing can be a bit tricky sometimes, so are there any scenarios I neglected to consider?

**Comment by nolimits4web** [comment]
Closing as not the case anymore in v2 router
