### ISSUE TITLE
critic issue on tabs related to router redirection & duplicated pages in dom

### ISSUE THREAD

**Issue by Matheo13** [framework7io/framework7-vue#183]
Hello,

There are few issues on the router, or tabs, I don't know from where it comes.
I forgot nested tabs after I saw some bugs and started using classic tabs (after reflexion it's certainly exactly the same bug).
More precisely, I simply can't redirect otherwise tabs aren't working anymore (which is a basic feature on mobile app).
(There is also a bug on classic tabs, even with the api, when I apply the show function, I have to use it this way in order to make it works, the active class is still missing)
```
this.$f7.showTab('#obsTab2', '#obsTab2', false, true);
```
(using 0.9.1)

I will try to take a look on it but I'm not sure where to search.
I use a basic routes like this:
```
export default [

  {
    path: '/projects/',
    component: require('./assets/vue/pages/projects.vue'),
  },

  {
    path: '/projects/:id/',
    component: require('./assets/vue/pages/project.vue'),
  },

  {
    path: '/protocols/',
    component: require('./assets/vue/pages/protocols.vue'),
  },

  {
    path: '/observation/:timestamp/',
    component: require('./assets/vue/pages/observation.vue'),
  },

]
```
There are 2 tabs per .vue file, then when I redirect, from /observation/:timestamp to projects/ I can't use tabs anymore. (Projects>project>observation)
I tried link href, API ($router.load) with every options.

Or maybe I made a mistake and I missed something?

Thanks.

**Comment by Matheo13** [comment]
It seems to be due to cached pages.
Not sure to be able to fix it.

**Comment by Matheo13** [comment]
Yup, definitly due to cached pages. Related issue:
https://github.com/nolimits4web/Framework7-Vue/issues/152
@nolimits4web 
I don't figure out how to fix it, I tried a lot of stuff and I don't how to use f7-vue with this pb.
Even if I do tabs by my hands and bind on creation, duplicated DOM could be a problem too.

![image](https://cloud.githubusercontent.com/assets/9080540/26601464/3054e1a4-4580-11e7-8a9f-c4d350bcfb75.png)
for instance here I have two "observation" page

**Comment by Matheo13** [comment]
seems to work if I set domCache: false, inside components/view.js line 110
But now I can have a white page on browser (default) back button (due to classes .page-on-left etc but if I disable it it doesn't work well either)

**Comment by Matheo13** [comment]
I had to disable manualy animations on pages too and it seems working.

**Comment by huangyuanyazi** [comment]
Excuse me ,do you resoved the problem?

**Comment by Matheo13** [comment]
Nop, I think I will try to debbug it with in mind to keep the default domCache and to try to remove duplicated pages only.
I let you know if come out with something.

**Comment by Matheo13** [comment]
I still have a problem actually with changes above, for instance, it doesn't reload correctly child views if you use the router to force a route, $route.lead('url') and not the back function. (There is also problem of the same kind with $.router.back())

**Comment by jvdh** [comment]
Yup, I'm having the same problem. It has been driving me nut! Any change for a fix soon, @nolimits4web #

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
