### ISSUE TITLE
allow individual modules to be used

### ISSUE THREAD

**Issue by vinstah** [framework7io/framework7-vue#219]
Hello, 

I would like to know how do I include only one component without having to add Vue.use(framework7-vue).
Currently I only need to use the Calendar component and would like to be able to include it like so:
`import { Calendar } from 'framework7-vue`
`export default {`
 ` components: {`
 `   Calendar`
`  }`
`}`
currently I see in dist/framework7.vue.js all the components are included in the component property this could potentially be exported at the bottom of the file.

It would also be nice if the components CSS was included in the component itself but that's not an issue right now

Thanks for the great work!

**Comment by nolimits4web** [comment]
Not possible at the moment, will be available in v2 version of plugin based on F7 v2

**Comment by nolimits4web** [comment]
Possible in v2
