### ISSUE TITLE
Watch on calendar props

### ISSUE THREAD

**Issue by lcaprini** [framework7io/framework7-vue#220]
Hi all,
I'm using with vue-i18n for app translation and I have a calendar with `month-names` and `day-names-short` initialized with `$t('monthsList')`, but when I change language I have no changes in f7-calendar component.
How can I have an update on calendar's props?

Thank you

**Comment by nolimits4web** [comment]
Yes, it won't work at the moment, as it is just a wrap around F7 Calendar API: https://github.com/nolimits4web/Framework7-Vue/blob/master/src/components/calendar.vue. As a workaround you can use native F7's inline calendar http://framework7.io/docs/calendar.html. And when you change translation you need to destroy calendar and initialize/create it again with new parameters

**Comment by nolimits4web** [comment]
Closing as not the case in v2, use vanilla F7 Calendar API
