### ISSUE TITLE
$router.load() doesn't work when changing only parameter and not the component

### ISSUE THREAD

**Issue by aishikaty** [framework7io/framework7-vue#221]
Hello, I have a page component and I want to change only it's parameter. I looks like this:
```javascript
var app = new Vue({
  ...
  router: [
    {
      path: '/my-page/:id/',
      component: 'my-page'
    },
})
```
And in the component when on url /my-page/1 method I call
```javascript
this.$route.load('/my-page/2')
```
But nothing happens. Do you have idea what could be wrong please?

**Comment by nirandas** [comment]
Have exact issue here. I'm navigating to another URL which points to same component with different param (dynamic route) and nothing happens. Is there any hook or event which we can get when same component is being reused?
@aishikaty  Were you able to solve this issue?

**Comment by nirandas** [comment]
I fixed it by setting allowDuplicateUrls to tru

````
    routes: Routes,
allowDuplicateUrls:true
````

**Comment by nolimits4web** [comment]
Fixed in v2
