### ISSUE TITLE
vmodel changes do not trigger "change" event in text-input, doesn't update Material Floating

### ISSUE THREAD

**Issue by mix3d** [framework7io/framework7-vue#224]
The watch function does not make sense for the `form-input` component. 

I would expect changes to the value to trigger a `change` on the input, which should update the "not-empty-state" class accordingly.

Right now, nothing happens when updating the v-model from outside the component, which means that the floating labels for Material designs do not get their correct state.

`components/form-input.vue`
```js
    watch: {
      value: function () {
        var self = this;
        if (!self.hasSelectModel) return;
        var $$ = self.$$;
        $$(self.$el).find('option').each(function (index, option) {
          if (self.value.indexOf(option.value) >= 0) option.selected = true;
          else option.selected = false;
        });
      }
    },
```

What is this even for?

**Comment by JasonKleban** [comment]
I think I had the same problem.  If I put `v-model` on the `<f7-input />`  I get errors about prop value and a watcher gets an InputEvent.  If I just use the `<input />` and other structures that would get rendered, but put the v-model directly on the input element all things work correctly.

**Comment by kevinqqnj** [comment]
**Cause**: `<f7-input>` wraps elements on `<input>`, so you cannot use v-model directly. here's a simple solution.
**Solution**: 
1) template:
`<f7-input type="text" placeholder="input your username" clear-button :value="username" @input="username = $event.target.value" />`
2) script:
```
  data() {
    return {
      username: '',
    }
  }
```
3) now it works!

**Comment by danielbprice** [comment]
I really feel like something about this needs to go into the documentation... I can confirm that the solution works but it took me forever to find this.
