### ISSUE TITLE
Action sheet bug when close through clicking the mask

### ISSUE THREAD

**Issue by yupeilin123** [framework7io/Framework7-Vue#230]
Hi there,

Please check the code below:
[Framework7-Vue-Simple-Template-master.zip](https://github.com/nolimits4web/Framework7-Vue/files/1255288/Framework7-Vue-Simple-Template-master.zip)

Step 1. click the button to show the action sheet.
Step 2. click the shadow mask to close the action sheet.
Step 3. click the button again, but the action sheet never shows. Here is the bug.

**Comment by rashnk** [comment]
how did you solve this ?? i have the same issuse

**Comment by yupeilin123** [comment]
yes, I solve this @rashnk
