### ISSUE TITLE
When sorting, the pull to refresh will start at the same time

### ISSUE THREAD

**Issue by yupeilin123** [framework7io/framework7-vue#233]
look it !
This is an example to show this Bug ！

When you sort from top to bottom ，you'll see that the pull to refresh starts at the same time .

[Framework7-Vue-Simple-Template-master.zip](https://github.com/nolimits4web/Framework7-Vue/files/1265845/Framework7-Vue-Simple-Template-master.zip)

**Comment by nolimits4web** [comment]
Fixed in v2
