### ISSUE TITLE
Nested Routes with Tabs not working since 0.9.0 release

### ISSUE THREAD

**Issue by ryaposov** [framework7io/framework7-vue#238]
Nested routes with tabs documented [here](https://framework7.io/vue/navigation-router.html#nested-routes) are not working since [0.9.0 release](https://github.com/framework7io/Framework7-Vue/releases/tag/v0.9.0). 

Tested on v0.8.5 - working.

**How to reproduce**
1. Create a starter project with this [template](https://github.com/centrual/cordova-template-framework7-vue-webpack)
2. Use [documentation](https://framework7.io/vue/navigation-router.html#nested-routes) to implement nested routes
3. Change framework7-vue version in package.json from 0.9.0 (and higher) to 0.8.5

**Comment by nolimits4web** [comment]
Must be fixed in v2 as it has new router
