### ISSUE TITLE
pushState not working with v2?

### ISSUE THREAD

**Issue by pi0** [framework7io/Framework7-Vue#240]
Hi. Sorry for asking too early, but as I'm working in parallel to experiment possibilities of vue-router support (alongside with f7 router), I can't make history mode working by adding `pushState: true` option. So my question is enabling pushState something so hard to add/fix to f7vue 2? Any hint would be really appreciated  :)

/ping @nolimits4web

**Comment by nolimits4web** [comment]
Hey, where do you add this parameter?

**Comment by pi0** [comment]
Hey and thanks for answering. Supposing Vue instance is created using `new Vue(app)`: 

```js
 app.pushState = true

 app.framework7 = {
        routes,
        pushState: true,
        params: {
            pushState: true
        },
        route: {
            params: {
                pushState: true
            }
        }
    }
```

Nothing works :( 

PS: I can share you reproduce repository if prefer. It is based on Nuxt.js.

**Comment by nolimits4web** [comment]
Ok, i see :) In v2 it has been moved under common `view` parameters (which is router) so it should be:
```
app.framework7 = {
  view: {
    pushState: true,
  }
}
```

But there still could be inconsistence behavior in case you have multiple views in the app. So it is better to do it on main view:
```
<f7-view :pushState="true">...</f7-view>
```

**Comment by pi0** [comment]
Ahh yes, it's working now using `view` key, I've to read source code more carefully :D BTW  adding `pushState` to component seems not working [prop](https://github.com/framework7io/Framework7-Vue/blob/v2/src/components/view.vue#L63) is not bound to any logic.

**Comment by ijry** [comment]
<f7-view :pushState="true">...</f7-view> not working
app.framework7 = {
  view: {
    pushState: true,
  }
}
not working too?

**Comment by nolimits4web** [comment]
http://framework7.io/vue/init-app.html

**Comment by CaioValentim** [comment]
Now to use PushState i need to use Vue Instance? I can not use them apart?

var app  = new Framework7({
  root: '#app',
  view: {
pushState: true,
}
....
});

**Comment by 1453alabanda** [comment]
thanks its work

app.framework7 = {
  view: {
    pushState: true,
  }
}

**Comment by jaideepghosh** [comment]
I tried to add `pushState: true`, In mobile browser if I'm pressing the back button, it is going back to the browser home screen. Any suggestion for this.

`// Init App
var app = new Framework7({
  id: 'io.framework7.testapp',
  root: '#app',
  theme: theme,
  **pushState: true,**
  data: function () {
    return {
      user: {
        firstName: 'John',
        lastName: 'Doe',
      },
    };
  },
  methods: {
    helloWorld: function () {
      app.dialog.alert('Hello World!');
    },
  },
  routes: routes,
  vi: {
    placementId: 'pltd4o7ibb9rc653x14',
  },
  panel: {
    swipe: 'left',
    leftBreakpoint: 768,
    rightBreakpoint: 1440,
  }
});`

**Comment by web-data-MrLi** [comment]
![image](https://user-images.githubusercontent.com/23130674/44759178-0cd5f900-ab6b-11e8-82fd-b8332afc296c.png)
It's not right to write this way.
