### ISSUE TITLE
IE 11 - Error in nextTick: "SyntaxError" When trying to change page

### ISSUE THREAD

**Issue by henry-geronimo** [framework7io/framework7-vue#252]
Hi, this happens only on IE 11 my App seems to be loaded well but when i try to change by clicking on an internal link i get this error.

```
[Vue warn]: Error in nextTick: "SyntaxError"
found in
---> <F7Pages>
          <F7View>
            <F7Views>
```

the child component is created (i can log stuff inside created hook) but the page is not changing, it seems like the router is not working...

Any Idea ?

**Comment by henry-geronimo** [comment]
UP !

I didn't find a way to solve this yet ...

**Comment by Andorxor** [comment]
Are you using the usual Vue-kebab-case tag names? 
`<f7-pages>
         <f7-views>
              <f7-view> ...`

**Comment by nolimits4web** [comment]
Does the default Vue Kitchen Sink works in IE 11?

**Comment by henry-geronimo** [comment]
Hi , i found the issue is caused by the property dynamic-navbar initialized on a f7-view, if i remove it, the new view is correctly displayed.

`<f7-view navbar-through :dynamic-navbar="true" main>`

However i still this param to be true, I tried to set this elsewhere like this 

`vue.$f7.mainView.params.dynamicNavbar = true`

but i still got the "SyntaxError" thing. Any Idea or workarounds ?

**Comment by henry-geronimo** [comment]
Sorry, yes it seems to be working fine
