### ISSUE TITLE
Cannot import intro project

### ISSUE THREAD

**Issue by markandrewkato** [framework7io/Framework7-Vue#259]
Hi, I've tried importing the package to my vuejs project as seen below.

`import Framework7 from 'framework7'`
`import Framework7Vue from 'framework7-vue'`

When I do console.log on both for testing, it returns undefined.

`console.log(Framework7)`

**Comment by wedog** [comment]
import { Framework7 } from 'framework7'
import { Framework7Vue } from 'framework7-vue'

**Comment by wedog** [comment]
webpack compile normally, but no matter what component you use, the browser  console 'did you register the component correctly?'

**Comment by markandrewkato** [comment]
Tried that too, showed another error

`Cannot read property '$' of undefined`

**Comment by markandrewkato** [comment]
Anyway, I've fixed it by changing the declaration to

```
let Framework7 = require('framework7')
let Framework7Vue = require('framework7-vue')
```

Thanks for helping!

**Comment by markandrewkato** [comment]
Reopening. Still showing an error.

`Unknown custom element: <f7-block-title> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

What I did is declared the Framework like shown above then integrated it with Vue as shown below:

```
let Framework7 = require('framework7')
let Framework7Vue = require('framework7-vue')

Vue.use(Framework7Vue)
```

I just followed the steps shown in the documentation.

**Comment by wedog** [comment]
This is the beta version of bug.
Use low version

**Comment by markandrewkato** [comment]
Got it. Thanks.
