### ISSUE TITLE
[v2] Optimize treeshaking

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-vue#261]
Adding Webpack as builder for the kitchen sink, tree shaking does not work, all the F7 / F7-Vue code exists in later bundles, even is I reference only one page. Configuration according https://webpack.js.org/guides/tree-shaking/

**Comment by nolimits4web** [comment]
Works now?

**Comment by scriptPilot** [comment]
Now, I have invited you to my test repo - maybe it helps you to see what happend / if the config is wrong:

- Run npm install
- Run npm run b

In the build/dev folder you find the js bundle (minified) and the css / css.min files.

**Comment by scriptPilot** [comment]
OK, I have seen it works, so I changed the title, because I cannot believe that the reduction is so less. So for me, the effort to define each page all the modules is currently higher than the benefit of saved file size.

Example:

```
require('framework7/dist/js/framework7.js')
require('framework7/dist/css/framework7.css')
require('framework7-vue/dist/framework7-vue.js')
```
Webpack 3 build, no compression: 1.73 MB

```
import Framework7 from 'framework7/dist/js/framework7.esm.bundle'
import Framework7CSS from 'framework7/dist/css/framework7.css'
import { Framework7Vue } from 'framework7-vue'
```
Webpack 3 build, no compression: 1.67 MB

But maybe I did something wrong? In both cases, F7/F7-Vue v2 used.

**Comment by nolimits4web** [comment]
Don't include bundle versions if you need to use some modules only. Bundle is a bundle, don't expect much of tree-shaking from there

**Comment by nolimits4web** [comment]
CSS is not related to tree-shaking, CSS inclusion is just a webpack hack

**Comment by pi0** [comment]
Hi. Just wanted to share some personal experiences from latest build variants while working on optimizing [nuxt7](https://github.com/nuxt-community/nuxt7) - A v2 based PWA app framework.
We tried adding custom build for both [less](https://github.com/nuxt-community/nuxt7/blob/master/lib/templates/framework7.less) and also [JS](https://github.com/nuxt-community/nuxt7/blob/master/lib/templates/framework7.js) for extra (non-core) components. The result was **tree shaking don't actually makes some magic even by compiling only needed parts from esm source** and lighthouse score of using bundled js versions is something reasonable for PWA apps.

**Comment by nolimits4web** [comment]
This is due to not perfect tree-shaking implementation of bundlers (Webpack and Rollup). If you run Buble or Babel over the whole final bundle package instead of separate modules you will get expected tree-shaking results. But anyway in next F7 update I’ll change it by putting separate components into separate folders/files to get correct tree-shaking results

**Comment by nolimits4web** [comment]
Closing, as stable v2's have separate components for better tree shaking
