### ISSUE TITLE
Different dynamic routes are identified as same URL

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-vue#264]
Route:

/accounts/:accountId/

Try to:

load /accounts/1/
load /accounts/2/

Does not work!

Workaround:

In view, add parameter `:allowDuplicateUrls="true"`

In my understanding, both dynamic routes should be handled as different URLs, what do you think, Vladimir? @nolimits4web

**Comment by nolimits4web** [comment]
Hey @scriptPilot, will check next week after come back from vacation

**Comment by scriptPilot** [comment]
@nolimits4web - Enjoy your vacation! Why did you close this issue?

**Comment by nolimits4web** [comment]
Accidentally

**Comment by nolimits4web** [comment]
Closing as not the case for v2
