### ISSUE TITLE
How to style .item-media correctly

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/Framework7-Vue#265]
Hey, I try to reduce the gap between the icon and the text in a list with scoped CSS. For the icon, it works well, but not for the `.item-media`.

I can change the background color when I remove `scoped` - with scoped, it doesn't work as well, but anyway, the gap I cannot close :-(

```
<template>
  <f7-popover>
    <f7-list>
      <f7-list-item title="Homepage">
        <div slot="media"><f7-icon material="add_box" /></div>
      </f7-list-item>
    </f7-list>
  </f7-popover>
</template>
<style scoped>
  .popover {
    width: 250px;
  }
  .item-media {
    min-width: 0;
    width: 25px;
    background: yellow;
  }
  .icon {
    opacity: 0.5;
  }
</style>

```

![bildschirmfoto 2017-10-31 um 18 43 47](https://user-images.githubusercontent.com/19615586/32239675-787b7de4-be6b-11e7-876e-1ecbaf8cde93.png)

**Comment by nolimits4web** [comment]
Check in inspector, you probably need more strict rule like .md .list .item-media {...
