### ISSUE TITLE
[Question] How to uncheck a list item checkbox

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/Framework7-Vue#267]
I have a list of items with a checkbox.

```
<f7-list-item
  v-for="(item, key) in items" :key="key"
  :title="item.title"
  checkbox checked
  :name="`item-${key}`"
  @change="handleItemChecked(key)" />
```

On select, I perform the database write ... in case there is an error, I want to uncheck the item again. What not worked is the following:

```
handleItemChecked(key) {
  this.$$(`input[name=item-${key}`).attr('checked', false)
}
```

Has anybody an idea how I could do that with the key as reference?

**Comment by nolimits4web** [comment]
It should be .prop instead of .attr
