### ISSUE TITLE
Smart-select is not respecting props

### ISSUE THREAD

**Issue by ryaposov** [framework7io/framework7-vue#269]
1. Property "smart-select-back-text" from [docs](http://framework7.io/vue/smart-select.html) is not respected. Tried `:smart-select-back-text="false"`, back button in navbar always has "Back" text and can't be overridden or changed. Also not working with string type.
Vue prints console error is using boolean for "smart-select-back-text" (as declared in docs).
`[Vue warn]: Invalid prop: type check failed for prop "smartSelectBackText". Expected String, got Boolean.`

2. Property "smart-select-searchnar-placeholder" misspelled in docs, should be "smart-select-searchbar-placeholder".
3. There is no option to turn off sliding navbar animation in smart-select. That is strange since sliding animation is not default one in the framework.

**Comment by nolimits4web** [comment]
http://framework7.io/vue/smart-select.html
