### ISSUE TITLE
Link is not working with a tab view and after app.addView

### ISSUE THREAD

**Issue by ceeji** [framework7io/framework7-vue#277]
After `app.addView` any link in this view will stop working.

for example, if we have a layout (HTML) as follow:

```html
   <f7-views tabs toolbar-fixed>
        <f7-view id="tab1" tab active>
            <f7-navbar sliding>
                <f7-nav-center sliding>Home</f7-nav-center>
            </f7-navbar>
            <f7-pages navbar-fixed>
                <f7-page name="home-1">
                    <f7-link href="/about/"></f7-link>
                </f7-page>
             </f7-pages>
        </f7-view>
    </f7-views>
```
So there is a view named `tab1` with a `tabs` prop. a `f7-link` is in this view. This is a basic tab layout.

This works like a charm, but if we have this code in `app.js`:

```js
this.mainView = this.myApp.addView('#tab1', { });
```

then when click the link it just can not redirect.

i have tried commenting the line above, and it works again.

so why i can not addView and keep the link working?

**Comment by nolimits4web** [comment]
Because f7-view already adds view automatically
