### ISSUE TITLE
<f7-view view-right> not rendering to <div class="view view-right">

### ISSUE THREAD

**Issue by HarisHashim** [framework7io/Framework7-Vue#280]
For instance this

```<f7-view id="right-view" navbar-through :dynamic-navbar="true" view-right>```

Render to

```<div class="view navbar-through" id="right-view" view-right>```

Expected

```<div class="view navbar-through view-right" id="right-view" >```

Expected behavior is observed from 

```<f7-view id="main-view" navbar-through :dynamic-navbar="true" main>```

Rendered to

```<div class="view view-main navbar-through" id="main-view">```

**Comment by nolimits4web** [comment]
Why did you get it should be rendered like that? `<f7-view id="right-view" navbar-through :dynamic-navbar="true" class="view-right">`
