### ISSUE TITLE
Latest npm package (v2.0.0-beta.5) broken

### ISSUE THREAD

**Issue by decates** [framework7io/Framework7-Vue#283]
I just started a new project and picked up the latest versions of framework7 (2.0.0-beta.16) and framework7-vue (2.0.0-beta.5). As far as I could tell, the latest version you've released off the v2 branch, with the big refactor, is completely broken (e.g. Framework7 doesn't have a 'Router' property). When I go back to framework7 v1.6.5 and framework7-vue 0.9.3 things start working again.

The v2 branch looks like a work in progress, but it's the version which will be picked up by anyone starting or adding Framework7 to a Vue project. Am I missing something?

Happy to create a minimum repro and be more specific if required, but wanted to check first.

**Comment by nolimits4web** [comment]
It is not broken. V2 is work in progress, yes. It has different API and many other things. You can check how the things is organised there in Kitchen Sink or wait until final release and official docs update
