### ISSUE TITLE
can't display the popup component

### ISSUE THREAD

**Issue by jiangtao-cool** [framework7io/Framework7-Vue#284]
`<f7-popup>some things</f7-popup>` ,  the rendered html is empty.

I check out the source popup.vue file,  found that there is a v-if=“opened” directive on the  slot 
```<template>
  <div class="popup"
    :class="classesObject"
    @popup:open="onOpen"
    @popup:opened="onOpened"
    @popup:close="onClose"
    @popup:closed="onClosed"
  >    
    <slot v-if="opened"></slot>
  </div>
</template>
```

I am wondering that to replace  v-if to v-show

**Comment by roboncode** [comment]
Same issue nothing renders when calling popup, the starter project has the same issue in the example 

`git clone https://github.com/nolimits4web/Framework7-Vue-Webpack-Template my-app`
