### ISSUE TITLE
2.0.0 release

### ISSUE THREAD

**Issue by pi0** [framework7io/framework7-vue#287]
Hi. I'm really looking forward to 2.0.0 (or maybe next beta) release of `framework7-vue` with latest dependency upgrades. I know you are busy working on core components, but if there are any blocking/needed changes can we help to contribute to faster release? Thanks.

**Comment by nolimits4web** [comment]
Hey!

With the already released of core 2.0.0, there is actually not very much left here. Here are the things i really need help with:

1. Convert the rest of F7 (old F7-Vue) components to new F7-Vue components (according to v2 api):
    - Searchbar
    - Timeline
    - Data Table
    - Modals: Actions, Sheet, Popover, Popup, Login Screen
    - Calendar & Date Picker
    - Picker (maybe)

2. When all components done, then align F7-Vue Kitchen Sink with F7's core Kitchen Sink (https://github.com/framework7io/Framework7/tree/master/kitchen-sink) but using Vue components instead.

All the new routing and other under-the-hood stuff is basically ready here.

**Comment by skycult** [comment]
I see that the awesome Framework7 2.0.5 is now out of beta status. F7-Vue is ready too?
Thank you.

**Comment by mgesmundo** [comment]
IMHO Framework7 is a super cool mobile framework (I used for a lot of time). When F7-vue 2 is released, it will jump forward and also a Nuxt integration will be great as @pi0 proposed. BUT... BUT... if F7 does not integrate the best Vue-Router it will continue to have a BIG limit.
@nolimits4web Do you plan to switch to Vue-Router?
All the best!

**Comment by nolimits4web** [comment]
@mgesmundo no plans to include Vue Router because it lacks for some features, also didn't find a way to implement there such complex page transitions as possible with F7 router

**Comment by mgesmundo** [comment]
@nolimits4web if you have a bit of time you can take a look at https://github.com/wangdahoo/vonic to see page transitions like F7 does (with navbar too). It is not comparable with F7 (F7 is super complete!) but the page animation works fine with standard vue-router.
Can you get some inspiration?

**Comment by pi0** [comment]
2.0.0 is released 🙌  Thanks @nolimits4web ❤️

**Comment by nolimits4web** [comment]
@pi0 how about adding Nuxt7 to [Framework7 Starter Apps](http://framework7.io/templates/)? PR to https://github.com/framework7io/framework7-website is welcome! And maybe Nuxt7 small tutorial to http://framework7.io/tutorials/? If you want we can post it on F7 blog

**Comment by pi0** [comment]
@nolimits4web Thanks for your offer. I'm definitely interested in adding Nuxt7 as an official starter template on the website. Also working on more docs and examples for N7 itself to make sure users will be able to smoothly get started. Will keep you informed about the progress and PR :)

**Comment by nolimits4web** [comment]
@pi0 awesome, thanks
