### ISSUE TITLE
use autocomplete throw exception

### ISSUE THREAD

**Issue by aloha1003** [framework7io/Framework7-Vue#289]
my framework7 version:  "^1.6.5",
    "framework7-vue": "^0.9.3"

I use framework7 autocomplete in my component.
my code : [Gist](https://gist.github.com/aloha1003/0d1d8606b24efe74530674330ba53f61)

when I foucs input , It will throw below exception : 
`Uncaught TypeError: Cannot read property 'top' of null
    at Autocomplete.a.positionDropDown`

**Comment by owen-mills** [comment]
I have the same issue. Did you solve it?
