### ISSUE TITLE
Tabs Component broken after loading data via Axios

### ISSUE THREAD

**Issue by Jaspur** [framework7io/framework7-vue#290]
I have a Components build with ```<f7-tabs>```:
Like this:
```
<f7-tabs swipable>
  <f7-tab id="tab1" active>Tab 1 content...</f7-tab>
  <f7-tab id="tab2">Tab 2 content...</f7-tab>
</f7-tabs>
```
This all works; swiping and clicking to go to a Tab.
But when I load some data via Axios to the Tabs (forms etc.), the Swiping functionality keeps existing, but clicking on a Tab only result in an active state of the color of the link, but it doesn't go to the Tab itself. It all does work when I don't load any data in from my API via Axios... What's wrong? Tabs need to be re-rendered after loading data? If so; how? If not; any idea what's causing this?

**Comment by stefblokdijk** [comment]
I'm experiencing the same error, did you find any solution @Jaspur ? When I switch from route and go back to the same route later (which creates a new component of the same page), the tabs are not moving and nothing animates inside of the tab when clicking on the navbar link that would show the tab

**Comment by Jaspur** [comment]
Conflict probably with naming of the IDs that are the same

________________________________

**Comment by stefblokdijk** [comment]
Yes that was right! Eventually I found out that when you go back to page 1 again, it will create a new component. So the id's are duplicated automatically.

I fixed it by adding dom-cache to my <f7-view>. That way it doesn't create 2 page components

**Comment by nolimits4web** [comment]
Closing as looks like resolved
