### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by hainuo** [framework7io/framework7-vue#293]
[package.json && main.js  gist](https://gist.github.com/hainuo/d10605b9113baf22ce18e8999525b220.js)

![image](https://user-images.githubusercontent.com/421861/34069287-d98530bc-e288-11e7-9c38-26edbf60e237.png)

when i use framework7-vue in my project,i got  this error;
i guess it  throws by  vuejs function `vue.use()` ,can you help me to fixed this error

**Comment by hainuo** [comment]
got one  more infomation

![default](https://user-images.githubusercontent.com/421861/34079100-6af245de-e361-11e7-8ad7-c3b5f35609ad.png)


The error is obvious； the variable window.framework7 is undefined

**Comment by Frank17** [comment]
yes, i have the same question

**Comment by jorgevilaca82** [comment]
Framework7 globals was'nt been injected on window object because of this line: https://github.com/framework7io/framework7/blob/0368764bd28d5f412fa89cc0b08e5417ee30b892/dist/framework7.esm.js#L41
this line evalute to false

**Comment by julian-ca** [comment]
Fixed it by manually assigning the `Framework7` variable into the `window` object.

```javascript

// Import F7
import Framework7 from 'framework7';

window.Framework7 = Framework7;

```

**Comment by nolimits4web** [comment]
Looks like you were trying to use F7-Vue v0.x with F7 2.x, they are not compatible, upgrade both libs to v2
