### ISSUE TITLE
can not handle calendar event

### ISSUE THREAD

**Issue by chenghsuan** [framework7io/framework7-vue#296]
Hi there~
I found a problem that f7-calendar component can not trigger call back event such as 
`onMonthAdd(c, monthContainer){
            self.$emit('monthAdd', c, monthContainer);
          },
          onDayClick(c, dayContainer, year, month, day){
            self.$emit('dayClick', c, dayContainer, year, month, day);
          },
          onMonthYearChangeStart(c, year, month){
            self.$emit('monthYearChangeStart', c, year, month);
          },
          onMonthYearChangeEnd(c, year, month){
            self.$emit('monthYearChangeEnd', c, year, month);
          }`
I used the component as following:
`<f7-calendar :style="style" @change="test" @monthYearChangEend="mychangeEnd"/>`

When I trace the browser developer mode found $emit event is not monthYearChangEend but monthyearchangeend 

![image](https://user-images.githubusercontent.com/9264001/34282640-0c1538e2-e702-11e7-82d7-c04fd7457c69.png)

so.. I try to change  framework7-vue.js like below and it is work now
![image](https://user-images.githubusercontent.com/9264001/34282700-723aa6e8-e702-11e7-8176-342fe0f83375.png)

`<f7-calendar :style="style" @change="test" @monthyearchangeend="mychangeEnd"/>`

 Do I use wrong way to handle the events?

**Comment by chenghsuan** [comment]
Hi~
You should not use camelCase  event name in Vuejs
Following is the reason:
https://github.com/vuejs/vue/issues/5186

**Comment by nolimits4web** [comment]
Closing as Calendar component removed from F7-Vue v2 in favour of using vanilla F7 Calendar API
