### ISSUE TITLE
accessing methods in f7-messages

### ISSUE THREAD

**Issue by rytyr** [framework7io/framework7-vue#297]
Hi @nolimits4web 
I need to access the messages method to manually scroll the messages. However, I can't find out how to access it. Could you clarify / give examples on how to use this **.f7Messages**  to access methods as described in [https://framework7.io/vue/messages.html](url) ?
````
<f7-messages :init="true" :scrollMessages="false">
        <f7-message v-for="message in messages">
        </f7-message>
</f7-messages>
````

Thanks before

**Comment by nolimits4web** [comment]
```
<f7-messages ref="messages" :init="true" :scrollMessages="false">
        <f7-message v-for="message in messages">
        </f7-message>
</f7-messages>
```

And later:
```
var messages = this.$refs.messages.f7Messages
```
