### ISSUE TITLE
how import framework7 package ?

### ISSUE THREAD

**Issue by TongDaDa** [framework7io/framework7-vue#298]
the official said

![2017-12-27 7 57 52](https://user-images.githubusercontent.com/23241188/34380980-7ff99e96-eb40-11e7-8d97-c9c60c5a5845.png)

However, I through the import did not see anything, let alone registered window

open node_modules see framework7 except dist folder no entry file

![2017-12-27 8 01 31](https://user-images.githubusercontent.com/23241188/34381041-ee6b02ca-eb40-11e7-8e9b-8192a0d56ad0.png)

window.framework7 is not defined. i have already import framework7 , why isn't framework7 ?

**Comment by TongDaDa** [comment]
Excuse me, How to use this import to introduce framework7 ?

**Comment by caiobiodere** [comment]
Did you fix this error? i had the same problem here

**Comment by cornelisse** [comment]
I am not an expert but perhaps if you change the following lines

```
import Framework7 from 'framework7/dist/framework7.esm.bundle.js'
import Framework7Vue from 'framework7-vue/dist/framework7-vue.esm.bundle.js'
```
and
`Vue.use(Framework7Vue)`
into
`Vue.use(Framework7Vue, Framework7)`
This works for version v2.

Ps,
This kind of question are more suitable to ask at the [F7 forum](http://forum.framework7.io/)
