### ISSUE TITLE
F7+Vue V2 pushState not working ...

### ISSUE THREAD

**Issue by thugic** [framework7io/framework7-vue#301]
I've read all the answers about the pushState: true option but it doesn't work for me when I add it to the kitchen-sink app configuration.
I added it in the app.js file as nolimits4web stated in one of his previous answers:

```
`// Import Vue
import Vue from 'vue';

// Import Framework7 Vue Plugin
import Framework7Vue from '../src/framework7-vue.js';

// Import Routes
import Routes from './routes.js';

// Install Plugin
Vue.use(Framework7Vue);
```

```
// Init Vue App
var app = new Vue({
    // Root Element
    el: '#app',
    // Framework7 Parameters
    framework7: {
      root: '#app', //Should be same as app el
      animateNavBackIcon: true,
      swipePanel: 'left',
      view: {
        main: true,
        pushState: true
      },
      routes: Routes,
      material: !Framework7.prototype.device.ios,
      notificationHold: '2000',
    },
    // Custom App Data
    data: function () {
 ........`
```

but it is still not working. (Even if I do npm run build and then try from the built bundle ...)

Any other way i can make this work?

Thanks in advance for your answers!
/cc @nolimits4web

**Comment by thugic** [comment]
Dumb question, just found out I was using the 0.9.4 version :(

Now, when I tried the V2 version turns out that it has lots of bugs in Chrome, when navigating between pages some pages stay in "overlay" so you can't see anything ...
![schermata del 2017-12-29 17-03-46](https://user-images.githubusercontent.com/22091704/34441226-9eb321b0-ecba-11e7-91f7-5143156c15fb.png)

Should I open a new issue?

Thanks guys ...

**Comment by nolimits4web** [comment]
Because it has different layout, check the v2 kitchen sink
