### ISSUE TITLE
2.0.0-beta.6: Uncaught TypeError: Cannot read property '$' of undefined

### ISSUE THREAD

**Issue by markwatney2016** [framework7io/framework7-vue#308]
I get this error message in my fresh installation:

```
Uncaught TypeError: Cannot read property '$' of undefined
framework7-vue.js:5214

at Object.install (framework7-vue.js:5214)
at Function.Vue.use (vue.js:4668)
at app.js:1
```

I just installed `vue.js`, `framework7` and `framework7-vue` via NPM. This is my `package.json` file:

    {
      "name": "framework7-vue-foo",
      "version": "0.1.0",
      "description": "A dummy project for learning purpose",
      "devDependencies": {},
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "Mark Watney",
      "license": "MIT",
      "dependencies": {
        "framework7": "^2.0.6",
        "framework7-vue": "^2.0.0-beta.6",
        "vue": "^2.5.13"
      }
    }

I then created an `index.html` file:

    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <title>Foo</title>
        <link rel="stylesheet" href="node_modules/framework7/dist/css/framework7.css">
        <link rel="stylesheet" href="css/app.css">
    </head>
    <body>
    <div id="app">
        <f7-statusbar></f7-statusbar>
    </div>
    <script src="node_modules/framework7/dist/js/framework7.js"></script>
    <script src="node_modules/vue/dist/vue.js"></script>
    <script src="node_modules/framework7-vue/dist/framework7-vue.js"></script>
    <script src="js/app.js"></script>
    </body>
    </html>

Ant this is my `app.js` file:

    Vue.use(Framework7Vue);
    new Vue({
      el: '#app',
      framework7: {
        root: '#app'
      }
    });

**Comment by nolimits4web** [comment]
It must be `Vue.use(Framework7Vue, Framework7);`
