### ISSUE TITLE
Using v2

### ISSUE THREAD

**Issue by etiennea** [framework7io/framework7-vue#309]
So if I understand other than some changes to the javascript part of F7 the main difference in v2 is you have to import and mount all components as such: 

` 
  import { f7Panel, f7View, f7Statusbar } from 'framework7-vue';
`
`
  export default {
    components: {
      f7Panel,
      f7View,
      f7Statusbar,
    },
  };
`

Is there a way we can mount all components by default as before?

**Comment by nolimits4web** [comment]
You can use bundle version `import Framework7Vue from 'framework7-vue/dist/framework7-vue.esm.bundle';` All component will be registered automatically in this case
