### ISSUE TITLE
How do I access the swiper instance in framework7 vue

### ISSUE THREAD

**Issue by carboni09** [framework7io/framework7-vue#310]
I need help on how to access the automatically initialized f7-swiper instance . The documentation says: If you use automatic initalization to init Swiper (with init:true prop) and need to use its Methods and Properties you can access its initialized instance by accessing **.swiper** component's property. I am not able to access this instance. any help would be much appreciated.

**Comment by nolimits4web** [comment]
You need to access component, in Vue, you can do it using refs https://vuejs.org/v2/guide/components.html#Child-Component-Refs 

After you have component, it will be available as `swiper` prop of component
