### ISSUE TITLE
[v2] framework7-vue-webpack-cordova-app-template out of date

### ISSUE THREAD

**Issue by kevinqqnj** [framework7io/framework7-vue#315]
**Issue:**
The Starter App Template: [framework7-vue-webpack-cordova-app-template](http://framework7.io/vue/templates.html#framework7-vue-webpack-cordova-app-template) is out of date, can not start with v2.

**Solution:**
The original author @centrual will not update any more.
According to the original template and new things in F7 v2, here's updated template, works with F7 v2 and F7-vue v2, https://github.com/kevinqqnj/cordova-template-framework7-vue-v2

Comments are welcome.

**Comment by nolimits4web** [comment]
Thanks. And looks like it was moved to another author https://github.com/caiobiodere/cordova-template-framework7-vue-webpack

Anyway, you can PR your template to the http://framework7.io/templates/ section to be discoverable for others

**Comment by nolimits4web** [comment]
Send PR to https://github.com/framework7io/framework7-website/blob/master/src/pug/templates/templates.yml
