### ISSUE TITLE
`import { Framework7Vue } from 'framework7-vue'` breaking change from v2.0.0-beta.5?

### ISSUE THREAD

**Issue by JasonKleban** [framework7io/framework7-vue#317]
```
import { Framework7Vue } from 'framework7-vue'
```

With framework7 either v2.0.5 & v2.0.6, between framework7-vue v2.0.0-beta.5 to v 2.0.0, something changed about the exports such that my webpack bundle is failing.  If I revert to v2.0.0-beta.5 it works again.

I get:

"export 'Framework7Vue' was not found in 'framework7-vue'

I've been trying all the different import variations to get it to work but I can't find the working one.  Do you know what relevant thing might have changed?

Thanks!

**Comment by nolimits4web** [comment]
Yes it was changed to default export, here is the correct way in https://github.com/framework7io/framework7-vue/blob/master/kitchen-sink/src/app.js
