### ISSUE TITLE
"[Vue warn]: Error in event handler for "f7Ready": "TypeError: Cannot read property 'create' of undefined"  (found in <Root>)" and others

### ISSUE THREAD

**Issue by JasonKleban** [framework7io/framework7-vue#318]
With [v2.0.0-beta.5](https://github.com/framework7io/framework7-vue/issues/317), are these errors at startup expected right now as known issues, or am I doing something wrong?

![image](https://user-images.githubusercontent.com/17498172/34956619-ffbb04b0-f9f7-11e7-8377-a15fc0ba0bb3.png)

```
[Vue warn]: Error in event handler for "f7Ready": "TypeError: Cannot read property 'create' of undefined"
(found in <Root>)

TypeError: Cannot read property 'create' of undefined
    at VueComponent.onF7Ready (framework7-vue.esm.js?23c4:3745)
```

**Comment by nolimits4web** [comment]
No it is not. Stable 2.0.0 released, you probably doing something wrong there

**Comment by JasonKleban** [comment]
OK, I think this the failure spot.  Why might `self.$f7.panel` be undefined here?  This is the second of five f7ready handlers.  And it happens twice, possibly once for the right panel and once for the left panel?

![image](https://user-images.githubusercontent.com/17498172/34957480-d19c92b6-f9fb-11e7-9c6f-671358308d88.png)

Here's my app.vue:

```html
<template>
    <div id="app">
        <f7-statusbar></f7-statusbar>
        <f7-panel left cover>
            <f7-view></f7-view>
        </f7-panel>
        <f7-panel right reveal>
            <f7-view></f7-view>
        </f7-panel>
        <f7-view url="/" :main="true"></f7-view>
    </div>
</template>
```

If I take out both panels, the errors go away.

**Comment by nolimits4web** [comment]
How did you include F7 library itself?

**Comment by JasonKleban** [comment]
Yes.  And what little I have so far works otherwise.  I'll close this case - I just put details in in case it helps you refine...  If you want to know about this case I'm happy to answer.

**Comment by nolimits4web** [comment]
So I guess you have just included core version of F7?

**Comment by JasonKleban** [comment]
I'm not sure - I didn't go out of my way to only include the core.  I `import Framework7 from 'framework7'` in my index.ts which `import app from './app.vue'` which `import { f7Panel, f7View, f7Statusbar } from 'framework7-vue'` and doesn't have anything else special.

**Comment by JasonKleban** [comment]
You're right!

I added this note to my framework7.d.ts readme:

> Assuming that you'll want to include the whole of framework7 library and you're using webpack, you need to alias 'framework7' to be resolved to the full bundle.  That way you can still say `import Framework7 from 'framework7'` in your code and these type definitions will get picked up by typescript, yet at runtime you'll get more than just the core.  I don't want to rename this module declaration, because it seems more flexible to alias thusly for your situation.
> 
> ```js
> resolve: {
>     alias: {
>       'framework7$': 'framework7/dist/framework7.esm.bundle'
>     },
> ```

https://github.com/JasonKleban/Framework7.d.ts/blob/v2/README.md

**Comment by ccwq** [comment]
I has same problem.

And i has resolved it.

important point is 

```
//right case
import Framework7 from "framework7/framework7.esm.bundle.js"
```



```
//wrong case
import Framework7 from "framework7/framework7.esm.js"
//or
import Framework7 from "framework7"
```

.

And i'm weekness in english.
