### ISSUE TITLE
How to use f7 components as  async components

### ISSUE THREAD

**Issue by WalterZou** [framework7io/framework7-vue#320]
In order to reduce the size of js bundle, can we import f7 components just when it is used?

**Comment by nolimits4web** [comment]
If you mean for router, then in v2 you can pass `async` route  http://framework7.io/docs/routes.html#async-route which you must resolve with Vue component declaration.

```
{
  path: '/some-route/',
  async(routeTo, routeFrom, resolve, reject) {
    const vueComponent = /* ... request something to get Vue Component here */
    // and then resolve it with component
    resolve({
      component: vueComponent,
    })
  }
}
```
I think webpack dynamic imports can help you here https://webpack.js.org/guides/code-splitting/#dynamic-imports

**Comment by WalterZou** [comment]
@nolimits4web thanks, i meant the build-in component of framework7-vue, such as 'login.vue' . Some components i would never use.

**Comment by J05HI** [comment]
Yeah how is this possible?
It's a must have in vue :)

**Comment by J05HI** [comment]
Yeah how is this possible?
It's a must have in vue :)

**Comment by nolimits4web** [comment]
Look at v2 KS https://github.com/framework7io/framework7-vue/blob/master/kitchen-sink/src/pages/about.vue It allows to import only modules you are using

**Comment by J05HI** [comment]
@nolimits4web
Thanks! ☺

**Comment by WalterZou** [comment]
@nolimits4web Thanks! 👍

**Comment by ulissepress** [comment]
Hi 

i tried to load a vue component async. but when i use this approach the history is broken (no back button, ecc.).

Here the code (the router paths definition):

`export default 
[
    { path: '/home',            name: 'home',       component: HomePage     },
    { path: '/about',           name: 'about',      async(routeTo, routeFrom, resolve) 
        {
            const vueComponent = () => import('./pages/AboutPage.vue');      
            resolve({ component: vueComponent })      
        } 
    },
    { path: '/pr-list',         name: 'pr-list',    component: PRListPage   },
];`
