### ISSUE TITLE
framework7@2.0.6 and framework7-vue@2.0.0 not working ?

### ISSUE THREAD

**Issue by Byambaa9119** [framework7io/framework7-vue#323]
![error1](https://user-images.githubusercontent.com/23717822/35086140-679d65a8-fc66-11e7-87ca-2a9d4b196dbd.png)
Hi,

I am using Laravel.
I installed framework7@2.0.6 and framework7-vue@2.0.0

My source code 

window.Framework7 = require('framework7')
window.Framework7Vue = require('framework7-vue')

import Routes from './routes.js'
import App from './App.vue'
import { store } from './store'

Vue.use(Framework7Vue)

new Vue({
  el: '#app',
  framework7: {
    root: '#app',
    routes: Routes
  },
  render: h => h(App)
})

These are error.

Unknown custom element: <f7-statusbar> - did you register the component correctly? For recursive components, make sure to provide the "name" option

Help me ! 

I want using framework7v2.

**Comment by skyliwq** [comment]
Vue.use(Framework7Vue,Framework7)

**Comment by wegorich** [comment]
Same error `Vue.use(Framework7Vue,Framework7)` doesn't helps

**Comment by nolimits4web** [comment]
for 2.x versions there is `Vue.use(Framework7Vue,Framework7)`. Check the v2 Kitchen Sink https://github.com/framework7io/framework7-vue/blob/master/kitchen-sink/src/app.js
