### ISSUE TITLE
Components missing [ f7-pages , f7-list-label ]

### ISSUE THREAD

**Issue by mikeskolari** [framework7io/framework7-vue#328]
I'm trying to use the Login screen vue component, but errors occur.
Following the official documentation at [https://framework7.io/vue/login-screen.html](https://framework7.io/vue/login-screen.html)
I get 
`[Vue warn]: Unknown custom element: <f7-pages> - did you register the component correctly?`
and 
`[Vue warn]: Unknown custom element: <f7-list-label> - did you register the component correctly?`

I'm using tag v2.0.0 and there is no pages.vue or list-label.vue file inside src/components folder.
If I go back to tag v0.9.4 these two files exist.

**Comment by nolimits4web** [comment]
There is no more these components in v2. Wait for v2 docs

**Comment by mikeskolari** [comment]
Thanks
