### ISSUE TITLE
[V2] Vue created() event called at wrong time?

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7-vue#329]
I have a project with f7-vue with 3 pages:

/root/ has a created() method that calls a REST api to load data for Vuex.
/step1/ shows a summary of already loaded data (there is no api call here).
/step2/ is a new blank page.

When I click on a link on /root/ to navigate to /step1/, then click on < Back, the api is not called (as expected).

When I click on a link on /step1/ to load /step1/, then < Back (now I'm on /step1/), the api is called (but I'm not yet on /root/!!!).

After that, if I hit < Back again, the api is not called.

It seems that the first page is being unloaded after /step2/ being loaded, and again is loaded in advance when I pop /step2/ out of the stack.

Is there a way I can make sure that api is called ONLY whan I'm really back to /root/??? (it doesn't make difference if I use created() or mounted(), AFIK).

**Comment by nolimits4web** [comment]
Everything is correct. F7 keeps two pages in DOM by default: current page and previous page in order to make swipe back to work. Otherwise you may disable preloadPreviousPage and iosSwipeBack in router settings
