### ISSUE TITLE
[v2] Unexpected object value with F7Button - v-model issue

### ISSUE THREAD

**Issue by baron159** [framework7io/framework7-vue#330]
When using v-model in the following example:
`
    <f7-list-item>
        <f7-label>Email</f7-label>
        <f7-input name="userEmail" placeholder="Email" type="email" v-model.trim="userEmail"/>
    </f7-list-item>
`

No matter what I type it is replaced with '[object Event]' in the text field. The same is true for the password field.  Not sure if this is an issue on my end or an error in the component.  I have included an image of what I am seeing.

I am using the most recent release of both framework7 and framwork7-vue

<img width="363" alt="screen shot 2018-01-22 at 5 12 19 pm" src="https://user-images.githubusercontent.com/8651821/35247248-b0f09188-ff97-11e7-9510-a0e6f753b0bb.png">

**Comment by nolimits4web** [comment]
`v-model` in v2 is not supported use @input + `:value` instead:
```
<f7-input name="userEmail" placeholder="Email" type="email" @input="userEmail = $event.target.value" :value="userEmail"/>

**Comment by baron159** [comment]
Thank you
