### ISSUE TITLE
Color-theme, no-shadow and other props (even class and style attributes) doesnt applying to Navbar

### ISSUE THREAD

**Issue by NikitaKA** [framework7io/framework7-vue#333]
I tried to set up color theme for `Navbar` and found that props (and/or attributes) doesn't applying to component tag.
```html
<f7-page class="foo" ptr @ptr:refresh="onRefresh">
   <f7-navbar style="background: black" class="test" color="red" color-theme="white" no-shadow>
      <f7-nav-left class="foo">
```

Result: page tag with `.foo` class, navbars `.left` with `.foo`, but `<div class="navbar">` is clean, without any classes and attributes.

**Comment by nolimits4web** [comment]
It happens because iOS theme uses single navbar container for all pages, and grabs only internal `navbar-inner`.  You can put empty navbar for iOS theme that will be reused:
```
<f7-view url="/" :main="true" class="ios-edges">
      <f7-navbar v-if="$theme.ios" color="red" color-theme="orange" text-color="green" :inner="false"></f7-navbar>
</f7-view>
```

**Comment by NikitaKA** [comment]
Thank you, now it works.

P.S. I thought that in v.2 it is not necessary to duplicate `navbar` tag and `view` for iOS. But it is good that only small part of it should be duplicated.
