### ISSUE TITLE
[Bug] Referenced icon missing

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-vue#334]
The icon is not found at the referenced source:

https://github.com/framework7io/framework7-vue/blob/ff97d3d1107aa7b22b95f86813dea1ff84feb0bf/kitchen-sink/css/app.css#L82

**Comment by nolimits4web** [comment]
It doesn't produce any issues, styles copied from original KS

**Comment by scriptPilot** [comment]
Building with parcel.js results in an error, if a mentioned resource is not available :-/
