### ISSUE TITLE
[v2] Why does the router doesn't work

### ISSUE THREAD

**Issue by wegorich** [framework7io/framework7-vue#336]
I have tabbed application:

**views/view1**
```javascript
import { DefaultPage } from "./vm/page-default"

export default {
    components: {
      DefaultPage
    },
    render(h) {
        return (<f7-view id="some-id" tab main navbar-fixed>
          <default-page/>
      </f7-view>);
    }
}
```

**routes.js**
```javascript
export default [
  {
      path: '/page-url-1/',
      component: require('./vm/page-1').default
  },
  {
      path: '/page-url-2/',
      component: require('./vm/page-2').default
  },
  {
      path: '/page-url-3/',
      component: require('./vm/page-3').default
  },
];
```

**app/app.js**
```javascript
import ViewOne from './views/view1';
import ViewTwo from './views/view2';
import ViewThree from './views/view3';

export default {
  render(h) {
    return (
      <div id="app">
        <f7-statusbar></f7-statusbar>
        <f7-views tabs>
          <ViewOne/>
          <ViewTwo/>
          <ViewThree/>
        </f7-views>
     </div>
    )
  }
}
```

**app.js**
```javascript
import App from './app'
import routes from "./routes"

const app = new Vue({
    framework7: {
        root: '#app',
        tapHold: true,
        disableContextMenu: true,
        touch: {
            tapHold: true,
        },
        tapHoldDelay: 500,
        /* Uncomment to enable Material theme: */
        // material: true,
        routes: routes,
        theme: 'ios'
    },
    ...App
})
```

At v1 version all works fine. So the problem, router not working at all. All times I click the link and expects the new page will loads by the path. Nothing happend.

Only issue I have in the console: 

```
framework7.esm.bundle.js:3328 Uncaught TypeError: Cannot read property 'push' of undefined
    at Router$1.pageComponentLoader (framework7-vue.esm.bundle.js:97)
```

**Comment by nolimits4web** [comment]
Will be good to see full code. Did you initialized F7-vue plugin correctly? It must be `Vue.use(Framework7Vue, Framework7)`. Also you can refer to official F7-Vue templates, they are updated to v2. For example https://github.com/framework7io/framework7-template-vue-simple

**Comment by wegorich** [comment]
@nolimits4web I'v prepare full feature app to show up the problem. Yeah I'd checked every sample of framework7 website, nothing helps. It may be architecture issue https://github.com/pirateminds/vue-framework7

**Comment by NikitaKA** [comment]
I have same problem. I just realized what happening (it took 2 days to understand). The problem is in <f7-view> which wrapped to custom component. If you put your <f7-view> right inside <f7-views> everything will work.

**Comment by nolimits4web** [comment]
Thanks @NikitaKA, pushed fix for this to consider such cases. @wegorich pay also attention to trailing `/` in your routes and links, must be the same
