### ISSUE TITLE
[object InputEvent] on inputs

### ISSUE THREAD

**Issue by etiennea** [framework7io/framework7-vue#338]
`<f7-input type="text" placeholder="Your name" v-model="value" :value="value" clear-button></f7-input>`

The addition on v-model to f7-input used to work out of the box. Now on keyup it changes to [object InputEvent] and I get an error in the console Invalid prop: type check failed for prop "value". Expected String, Number, Array, got InputEvent.

Guessing this is a bug, because it is useful to be able to bind v-model to f7-input! Thanks!

**Comment by almazk** [comment]
try in this way
`<f7-input type="text" placeholder="Your name"  
      :value="value" 
      @input="value = $event.target.value"  
      clear-button></f7-input>`

**Comment by etiennea** [comment]
Works! Thanks! Still the v-model="value" is a more standard vue syntax and more concise, would be nice if that can be made to work?

**Comment by nolimits4web** [comment]
Sorry, no `v-model` support. It works very buggy and unpredicted on custom components. It is much more bulletproof to just use `:value` + `@input` handler

**Comment by etiennea** [comment]
Maybe a line about this could be added to the vue docs, because it is a common thing to try and bind to the input component.

**Comment by nolimits4web** [comment]
Sure, will added.
