### ISSUE TITLE
Swiper `preventClicks` does not prevent click on `f7-link`

### ISSUE THREAD

**Issue by NikitaKA** [framework7io/framework7-vue#339]
If you start swiping by tapping on `<f7-link>` it will be clicked after `touchend` even if `preventClicks` is `true`.

In previous version (0.9.4) it works fine.

```html
<f7-tabs swipeable>
    <f7-tab class="page-content" tab-active>
        <f7-link href="/about/">Will be clicked</f7-link>
    </f7-tab>
    <f7-tab class="page-content">
        <a href="/about/">Will be clicked too</a>
    </f7-tab>
</f7-tabs>
```

**Comment by NikitaKA** [comment]
I've updated my repo with `swiper` branch to show you the problem: https://github.com/NikitaKA/f7testapp/tree/swiper

**Comment by NikitaKA** [comment]
I've solved the problem by adding `no-fast-click` property to `f7-link`. I don't know if it okay that we have to use this prop, so I will not close this issue.

**Comment by nolimits4web** [comment]
Looks like it is issue with the core F7, doesn't related to F7-Vue

**Comment by nolimits4web** [comment]
Ok, actually it is a Swiper issue that stops propagation on touchmove event. To avoid this just add `data-touch-move-stop-propagation="false"` attribute on swipeable tabs
