### ISSUE TITLE
Pull To Refresh doesn't work

### ISSUE THREAD

**Issue by almazk** [framework7io/framework7-vue#340]
I have migrated my application to V2. In the case when we use the feature of refreshing page by pulling down doesn't work. 
The code as shown in example
`<f7-page pull-to-refresh @ptr:refresh="onRefresh"><f7-navbar title="My App"></f7-navbar><p>Page content</p></f7-page>`

produces:

`<div data-v-513f865e="" class="page page-current" pull-to-refresh=""><div data-v-513f865e="" class="navbar"><div class="navbar-inner sliding"><div class="title">My App<!----></div></div></div><div class="page-content"> <p data-v-513f865e="" class="">Page content</p></div></div>`

and there is no reaction. 

My template.vue is:
`<template>    <f7-page pull-to-refresh @ptr:refresh="onRefresh">        <f7-navbar title="My App"></f7-navbar>        <p>Page content</p>    </f7-page></template><script>    export default {        name: "refresh",        methods: {            onRefresh(event, done) {                console.log('refresh')                done();            }        },    }</script>`

In Kitchen-sink demo, there are also class as **ptr-content** after **page-content**.
This is bug or am I doing something wrong?

**Comment by NikitaKA** [comment]
`pull-to-refresh` directive changed to `ptr`

**Comment by almazk** [comment]
thanks a lot, it works
