### ISSUE TITLE
Router stops working at the last step of `back` if there are more than one level of nesting

### ISSUE THREAD

**Issue by NikitaKA** [framework7io/framework7-vue#341]
Here is an example of what is going on (some content blurred):
![Example](http://g.recordit.co/so57CNfiLv.gif)

There are no errors thrown.

**Comment by nolimits4web** [comment]
Something wrong is happening here. Because i can't see such issue in Vue Kitchen Sink. Do you have some live example with the issue?

**Comment by NikitaKA** [comment]
@nolimits4web https://github.com/NikitaKA/f7testapp

Tried to clear out my app as much as I could, sorry if there still some garbage.

**Comment by nolimits4web** [comment]
It is because you don't have your home route. I recommend you to load the home page as component via routes

**Comment by NikitaKA** [comment]
Hmm, tried to do that, but I have strange feeling that something is wrong.

My `app.vue` was:

```html
<div id="app" class="framework7-root">
    <f7-statusbar></f7-statusbar>
    <f7-views tabs>
        <view-general></view-general>
        <view-announces></view-announces>
        ...
        <popup-menu></popup-menu>
        ...
        <f7-toolbar tabbar labels toolbar-bottom-md>
            ...
        </f7-toolbar>
    </f7-views>
</div>
```

Now, I moved this to component and load via routes:

`app.vue`

```html
<div id="app" class="framework7-root">
    <f7-statusbar></f7-statusbar>

    <f7-view url="/"></f7-view>
</div>
```

`home.vue`
```html
<template>
    <f7-views tabs>
        <view-general></view-general>
        <view-announces></view-announces>
        ...
        <popup-menu></popup-menu>
        ...
        <f7-toolbar>...</f7-toolbar>
    </f7-views>
</template>
```

`routes.js`
```javascript
import HomePage from './views/home';

export default [
    {
        path: '/',
        component: HomePage
    }
]
```
But its wrong if `f7-views` is inside `f7-view`, is it?

These changes did not fix the problem, furthermore now routes transition is... freezing slightly.

P.S. Relying on picture above: problem occurs inside `<popup-menu>` popup.

**Comment by nolimits4web** [comment]
Route component must return page, check how it is done here https://github.com/framework7io/framework7-template-vue-webpack/tree/master/src

**Comment by NikitaKA** [comment]
I got it! It is necessary to place **ALL** pages (if you are going to navigate through routes inside them) into separate components and load them through `routes` too.

```html
<f7-view>
    <f7-navbar v-if="$theme.ios" color-theme="white" :inner="false"></f7-navbar>
    <f7-page>...</f7-page>
</f7-view>

Turns to:
```html
<f7-view url="/somepage/">
    <f7-navbar v-if="$theme.ios" color-theme="white" :inner="false"></f7-navbar>
</f7-view>
```
