### ISSUE TITLE
Popup does not opened if other popup already opened

### ISSUE THREAD

**Issue by NikitaKA** [framework7io/framework7-vue#342]
It was possible to do that in older version (0.9.4), but now it is an error:

```javascript
Uncaught TypeError: Cannot read property 'f7Modal' of undefined
    at Object.open (framework7.esm.bundle.js?c501:13)
    at Framework7$1.openPopup (framework7.esm.bundle.js?c501:13)
    at eval (framework7.esm.bundle.js?c501:13)
    at Array.forEach (<anonymous>)
    at eval (framework7.esm.bundle.js?c501:13)
    at Array.forEach (<anonymous>)
    at Framework7$1.handleClicks (framework7.esm.bundle.js?c501:13)
    at eval (framework7.esm.bundle.js?c501:13)
    at Array.forEach (<anonymous>)
    at eval (framework7.esm.bundle.js?c501:13)
```

**Comment by nolimits4web** [comment]
Hi do you do it?

Kind Regards,
Vladimir Kharlampidi

**Comment by NikitaKA** [comment]
After deeper investigation I found that it was my mistake (misspelled id, sorry), **BUT**, I found real bug with two popups opened. `<f7-link popup-close></f7-link>` inside second popup closes first popup, not second. So I need to click `<f7-link>` twice to close second popup.

`<f7-link popup-close="#popup2"></f7-link>` doesn't work too.

I've updated my repo to show you that problem.

https://github.com/NikitaKA/f7testapp

**Comment by nolimits4web** [comment]
I can add such option, but it is not a good use case to have more than one popup opened at once. As a workaround:
- before open second, close first one
- use custom handler for such link and close both popups in this handler

**Comment by NikitaKA** [comment]
I agree with you. Two popup was the fastest way to implement my needs. :) I will try to use your workaround, thank you.

**Comment by NikitaKA** [comment]
@nolimits4web However, I want to draw your attention on the fact that `popup-close='#popup-id'` doesn't work.

Thanks for help!

**Comment by vousys** [comment]
@NikitaKA this could help you too:    

"closeByBackdropClick: When enabled, popup will be closed on backdrop click"

```
var app = new Framework7({
  popup: {
    closeByBackdropClick: false,
  }
});
```
