### ISSUE TITLE
How to make <f7-swiper> a virtual slide in framework7 vue

### ISSUE THREAD

**Issue by carboni09** [framework7io/framework7-vue#343]
Good day, kindly share any insight on creating a virtual slide with framework7 vue. the init prop is true, however will the “virtual” parameter be in the  : param prop ? Any help will be much appreciated. cheers

**Comment by nolimits4web** [comment]
Well, in same way:
```
<swiper :params="{virtual: {slides: virtualSlides}}"></swiper>
```
```
export default {
  computed: {
    virtualSlides() {
      //return virtual slides array here
    },
  }
}
