### ISSUE TITLE
F7MessageBar undefined $ref.textarea

### ISSUE THREAD

**Issue by xavi-ortega** [framework7io/framework7-vue#344]
My code:

> 
    <f7-page>
        <f7-messages>
            <f7-message v-for="message in messages"
                        :key="message.text" 
                        :text="message.text" 
                        :type="message.type"></f7-message>
        </f7-messages>
        <f7-messagebar send-link="Enviar" @submit="onSend"></f7-messagebar>
    </f7-page>

When I click on send button it shows this error:

[Vue warn]: Error in event handler for "click": "TypeError: Cannot read property 'value' of undefined"

found in

--- <F7Link>
       <F7Messagebar>
         <F7Page>
           <Chat> at src\pages\chat.vue
             <F7View>
               <App> at src\app.vue
                 <Root>

I checked the source code and my guess is that $refs.area is undefined

    onClick(event) {
        const value = this.$refs.area.value;
        const clear = this.f7Messagebar ? this.f7Messagebar.clear : () => {};
        this.$emit('submit', value, clear);
        this.$emit('send', value, clear);
        this.$emit('click', event);
    },

**Comment by lenlch** [comment]
I also got this error, how can I fix it？ Thanks.

**Comment by xavi-ortega** [comment]
I fixed it by copying his component to a new component made by me, and then
I fixed the errors.
I don't remember what I did, but it didn't take too much
