### ISSUE TITLE
Problem with centering `f7-nav-title` after `f7-nav-right` resize

### ISSUE THREAD

**Issue by NikitaKA** [framework7io/framework7-vue#346]
If I use dynamic icons in `navbar` there is a problem:
![Example](http://g.recordit.co/lTlBd9L0nU.gif)

In `0.9.4` it works fine:
![Example](http://g.recordit.co/7BFFHCnri3.gif)

**Comment by nolimits4web** [comment]
What is "dynamic" icon

**Comment by NikitaKA** [comment]
Something like that:
```html
<f7-nav-right>
   <f7-link v-if="currentTabShown === 1" @click="toggleFontSize" class="toggle-fontsize">Аа</f7-link>
   <f7-link v-if="currentTabShown === 2" icon-material="search" popup-open="#search"></f7-link>
</f7-nav-right>
```

**Comment by NikitaKA** [comment]
I've made repo with example: https://github.com/NikitaKA/f7testapp/tree/navbar

**Comment by NikitaKA** [comment]
It seems that this is not `framework7-vue` problem, but `framework7`.

I found a workaround:
```javascript
this.$f7.navbar.size(navbarEl)
```
Call it every time after `f7-nav-right` size changed.
