### ISSUE TITLE
Swiper doesn't initializing properly in hidden views

### ISSUE THREAD

**Issue by NikitaKA** [framework7io/framework7-vue#347]
Example: https://github.com/NikitaKA/f7testapp/tree/swipersinviews

If we have two tabbed views:

`app.vue`
```html
<f7-views tabs>
  <f7-view id="view1" tab tab-active url="/view1/"></f7-view>
  <f7-view id="view2" tab url="/view2/"></f7-view>

  <f7-toolbar tabbar>
    <f7-link text="View 1" href="#view1" tab-link tab-link-active></f7-link>
    <f7-link text="View 2" href="#view2" tab-link></f7-link>
  </f7-toolbar>
</f7-views>
```

And inside these views we have swipeable tabs:

`view1.vue`
```html
<f7-tabs swipeable>
  <f7-tab id="my-tab1" tab-active class="page-content">
    <menu-entry>View 1 Tab 1 Item 1</menu-entry>
    <menu-entry>View 1 Tab 1 Item 2</menu-entry>
    <menu-entry>View 1 Tab 1 Item 3</menu-entry>
  </f7-tab>
  <f7-tab id="my-tab2" class="page-content">
    <menu-entry>View 1 Tab 2 Item 11</menu-entry>
    <menu-entry>View 1 Tab 2 Item 12</menu-entry>
    <menu-entry>View 1 Tab 2 Item 13</menu-entry>
  </f7-tab>
</f7-tabs>
```

Swiper will not initialize properly on second, not active (and hidden) view.

The only **workaround** I've found is to set all views to `display: block` and `position: absolute` so they are always visible and swiper init properly.

**Comment by nolimits4web** [comment]
This is due to Swiper design. It is impossible to detect the size of something hidden. So you can:

* Place Swiper under `v-if` condition and show it when the tab becomes active/visible
* Or try to enable its `observer` and `observeParents` parameters
