### ISSUE TITLE
[v3] f7-input error-message not working

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7-vue#348]
This code
```
 <f7-list-item>
    <f7-label>Número</f7-label>
    <f7-input type="text" readonly placeholder="(não informado)" :value="currentAddress.streetNumber"  :info="currentAddress.streetNumber ? '' : 'Where is my error-message?'" :error-message="currentAddress.streetNumber ? '' : 'Informe o número da rua na pesquisa!'" required validate />
</f7-list-item>
```

results in this output

![image](https://user-images.githubusercontent.com/379339/35749635-5c1a59aa-0839-11e8-8c85-7bbb8cfb693a.png)

Can't figure out a way to error-message show a red warning when I tell it so.

BTW, copying the sample

```
<f7-input type="text" placeholder="Enter number" info='With custom error message' error-message="Only numbers please!" required validate pattern="[0-9]*" clear-button></f7-input>
```

only works sometimes.
I could not figure out why exactly the red warning vanishes =\

This form is filled by Google Maps and my intent here is to mark the field Street Number with a red warning if Google Maps didn't filled it (the field is read-only, as the user must use Google Maps autocomplete to fill the entire address).

**Comment by nolimits4web** [comment]
Yeah, it works a bit different. Just add it as a prop without condition. And it will be shown/hidden automatically by F7 when it is required

**Comment by nolimits4web** [comment]
If the form fills automatically then it probably doesn't trigger `input/change` event. So you can call `$f7.input.validate(inputEl)` to force validation check the validity
