### ISSUE TITLE
Ability to change f7-view params after init

### ISSUE THREAD

**Issue by ryaposov** [framework7io/framework7-vue#349]
Seems `<f7-view>` component doesn't react to props change (like `iosDynamicNavbar`) after it was initialized.

It would be nice to have the ability to configure it depending on page or any other thing.

Is there a way maybe to re-init view with new options? Or to make it reactive.

**Comment by nolimits4web** [comment]
No, it won't work, and usually it is not required. Enabling/disabling iosDynamicNavbar won't be possible as well. As the View and Router do a lot of stuff on init depending on init parameters. 

> Is there a way maybe to re-init view with new options?

If you have f7-view with `v-if="showView"` and then will change showView to `false` and then to `true` again, then Vue will just recreate View with required parameters
