### ISSUE TITLE
[V2] Passing context object in route.navigate() and access it in page data

### ISSUE THREAD

**Issue by emuthomi** [framework7io/framework7-vue#352]
I am having issues passing a context object in the router and accessing the same in page data.
My code is as below:

```
// other code
hireSomeone: function () {
      var person = this.user;
      var app = this.$f7;
      var options = {
        context: {
          candidate: person
        }
      };
      app.dialog.alert('You are about to hire ' + person.name + ' Click ok to proceed to Job Creation', function () {
        // navigate to job creation page 
        app.views.main.router.navigate('/job-create/', options);
      })
},
// more code
```

Then in job-create.vue I have this code to access the context object

```
// other code
created () {
},
watch: {
},
on: {
    pageInit: function (e, page) {
         console.log(page.context)
         console.log(page.route.context)
     },
     pageAfterOut: function () {
         // page has left the view
     },
},
methods: {
},
// more code

```
page.route.context and page.context are all undefined in the next page navigated. In fact there is no context object in the page as described here http://framework7.io/docs/page.html#page-data

**Comment by kevinqqnj** [comment]
page.route.context and page.context are only used for Dom7 template.
`context (object) - additional Router component or Template7 page context`

If you want to pass params when routing, simply using: 
1) routes.js
```
{
    path: '/job-create/:options',
    component: require('./PathTo/job-create.vue')
  },
```
2) Sender .vue page
```
let person = {name: 'Bob', age: 20}
let options = { candidate: person }
this.$f7router.navigate('/job-create/' + JSON.stringify(options))
```
3) Receiver .vue page
```
let param = this.$f7route.params.options
console.log(JSON.parse(param))
```

**Comment by emuthomi** [comment]
That method is inefficient for passing a large object or many objects. Can this page.context feature be considered to be added in the vue templates? At least to maintain compatibility with the Dom7 template.

**Comment by nolimits4web** [comment]
Will add it $f7Route property for such case

**Comment by emuthomi** [comment]
It will really be helpful. Am sure there are many devs wondering how to go about it after switching to F7 Vue.

**Comment by kevinqqnj** [comment]
If want to pass large content between pages, you should use "Vuex"!

**Comment by nolimits4web** [comment]
Closing as it is done in latest F7 release. So the `context` object will be in `route`

**Comment by tribalboy3000** [comment]
Could you please provide an example on how to use it as I have the same question. Also what version is this added in?

**Comment by kozmanbalint** [comment]
I use it like this in the receiver .vue page:

```
data() {
  return {
    myDataFromContext: this.$f7route.context.myData
  }
}
```
Where myData comes from the sender .vue.
