### ISSUE TITLE
[v2] - how to work with f7-input and v-model?

### ISSUE THREAD

**Issue by petericebear** [framework7io/framework7-vue#356]
```
    <f7-list form>
            <f7-list-item>
              <f7-label>Gebruikersnaam</f7-label>
              <f7-input v-model="username" placeholder="Gebruikersnaam" type="text"></f7-input>
            </f7-list-item>
            <f7-list-item>
              <f7-label>Wachtwoord</f7-label>
              <f7-input v-model="password" type="password" placeholder="Wachtwoord"></f7-input>
            </f7-list-item>
          </f7-list>
```

This is not working but how to use it in this way?

```
    data() {
     return () {
        username: null,
        password: null
     }
    }
```

**Comment by emuthomi** [comment]
I use v-bind 

```
<f7-input v-bind:value="username" placeholder="Gebruikersnaam" type="text"></f7-input>

```

**Comment by lrbalt** [comment]
two way binding using v-model worked on v1, but not on v2. The type of the value seems to be an Event instead of string/number/bool. Using v-model on a checkbox does not work anymore too

I had to resort to using the click event to retrieve the values from the form...

**Comment by morrislaptop** [comment]
This is a ridiculous bug!

**Comment by nolimits4web** [comment]
It is not a bug, it is by design. v-model is not supported on F7 v2 components, it can be easily replaced with value+@input:
```
<f7-input type=“text” :value=“someVar” @input=“someVar = $event.target.value”>
```

**Comment by morrislaptop** [comment]
Why would you not support standard Vue conventions? Why would you design it this way?

**Comment by nolimits4web** [comment]
I didn’t design it. This is how v-model works. No v-model support because it brings more issues with less flexibility

**Comment by lrbalt** [comment]
fair enough. perhaps you could add this solution (value+@input) to the documentation since `v-model` is a basic use of vue?

**Comment by morrislaptop** [comment]
@nolimits4web would you be open to a f7-model like directive pull request?

**Comment by caiotarifa** [comment]
What about create an intermediate component to solve this problem?

This doesn't work 100% because there is many tricks that depend of `this.$parent` and unfortunately we can't do something like `this = this.$parent`.

```
<template>
  <component :is="tag" :value="value" v-bind="attributes" @input="onInput" v-on="events" />
</template>

<script>
export default {
  props: {
    list: {
      default: false,
      type: Boolean
    },

    value: {
      required: true,
      type: [Number, String]
    }
  },

  computed: {
    attributes () {
      return this.$attrs
    },

    events () {
      return this.$listeners
    },

    tag () {
      return this.list ? 'f7-list-input' : 'f7-input'
    }
  },

  methods: {
    onInput (event) {
      this.$emit('input', event.target.value)
    }
  }
}
</script>
```
