### ISSUE TITLE
[v2] How to work with login pages

### ISSUE THREAD

**Issue by manish2535** [framework7io/framework7-vue#358]
I am using the Framework7 Vue Webpack starter pack.

My default page ('/') is a login page.  My plan is to run a xhr request as soon as any page in the app is requested. 

1. So I tried putting the isLoggedIn() call in the onF7Ready(f7). If logged in I thought I would use this to take the user to the home screen - self.$f7router.navigate('/home/'); else I would take the user to the Login page. Then I learnt the $f7router is only accessible in the Route Components.
2.  Then I thought I will put the isLoggedIn() check in each and every page's pageInit(). So I tried putting that code in the login.vue file in
```
on: {
    pageInit(e) {
```
The $f7router is available here but the self.$f7router.navigate('/home/'); does not work. The same self.$f7router.navigate('/home/'); however does work if I use it in one of the methods in the same login.vue file.

Even if the above code did work, there must be a better way of checking if a user is logged in and then do things in a much better way then I am doing. All my routes except for the  ('/') require authentication. 

Can anyone tell me how I should approach this very standard issue? Thanks a lot.

**Comment by nolimits4web** [comment]
Router navigate won't work in pageInit because routing is still in the process. I can recommend you the following app structure:
```html
<div id="app">
  <f7-view v-if="$root.isLoggedIn" url="/"></f7-view>
  <f7-login-screen v-if="!$root.isLoggedIn">
    ...
  </f7-login-screen>
</div>
```

**Comment by nolimits4web** [comment]
So when you set `isLoggedIn` prop on app root then you will have main view, otherwise you will have login screen. And if you have api calls then it is better to check and set the `isLoggedIn` there

**Comment by manish2535** [comment]
Thanks. I will try it out and post results here.
