### ISSUE TITLE
Up-to-date documentation

### ISSUE THREAD

**Issue by Kirpich634** [framework7io/framework7-vue#360]
I ran into a problem. Almost everything presented in the documentation, examples of using the F7 Vue Component do not work, while the F7 itself works fine.
Specific examples:

```
new Vue({
  el: rootNode,
  template: '<vue-app/>',
  components: {
    "vue-app": App
  },

  framework7: {
    root: rootNode,
    routes: Routes
  },
  methods: {
    onF7Ready(f7) {
      console.log("onF7Ready");
      console.log(this);
      // do some f7 related logic
      f7.dialog.alert('App initialized');
    }
  },
  created: function () {
    setTimeout(() => {
      console.dir(this);
    }, 1000);
  },
});
```
Context extensions: 

```
this.$f7
this.$$
this.Dom7
this.$device
this.$request
this.$utils
this.$theme
```

in the `this` do not exist.

Methods Extensions:

`onF7Ready`

is not called.

Maybe I'm doing something wrong?
Or is the documentation really outdated?
If so, tell me how I can work with your frameworks, or what version of the documentation is relevant?

**Comment by nolimits4web** [comment]
Official docs is for v2 and it is up to date. Check the starter templates at http://framework7.io/templates/, you probably doing something wrong
