### ISSUE TITLE
[V2] Async Lazy Loading of Vue component (page) is not working

### ISSUE THREAD

**Issue by ulissepress** [framework7io/framework7-vue#362]
Hi,

i tried to load a vue component async. but when i use this approach the page is loaded but the history is broken (no back button, ecc.).

Here the code (the router paths definition):

```
{ 
    path: '/about',  
    name: 'about',  
    async(routeTo, routeFrom, resolve) 
    {
         const vueComponent = () => import('./pages/AboutPage.vue');      
         resolve({ component: vueComponent })      
    } 
}
```

Instead if I use the syntax (no arrow function):

`const vueComponent = import('./pages/AboutPage.vue');`

then is working, but the **component is not anymore lazy-loaded** (is loaded with an async request but immediately on the app load, not when the page is effectively requested).

PS: I am using Framwork7-Vue v2

**Comment by nolimits4web** [comment]
Well, with this definition `const vueComponent = () => import('./pages/AboutPage.vue'); ` you have a function, not the component. You have to load component then and then call `resolve` with a component

**Comment by nolimits4web** [comment]
Try the:
```
const vueComponent = () => import('./pages/AboutPage.vue');
console.log(vueComponent());
```
What do you see in console?

**Comment by ulissepress** [comment]
Hi

vueComponent() is returing a Promise.

I tried this, but still not working:

```
{ path: '/about',           name: 'about',      
        async(routeTo, routeFrom, resolve) 
        {
            const vueComponent = () => import('./pages/AboutPage.vue');

            console.log('vueComponent', vueComponent());  // ==> Output: Promise

            vueComponent().then(vc => 
            {
                console.log('v inside the promise', vc);
                resolve( { component: vc } );
            });
        } 
    }

```

**Comment by nolimits4web** [comment]
And what is the output for `console.log('v inside the promise', vc);` ?

**Comment by nolimits4web** [comment]
Ah try not to call `vueComponent()` twice (remove it from first console.log)

**Comment by nolimits4web** [comment]
I will add notes about it to documentation

**Comment by ulissepress** [comment]
Thank you... your suggestion was key to find the solution :+1:
