### ISSUE TITLE
[v2] f7-range events not working

### ISSUE THREAD

**Issue by lrbalt** [framework7io/framework7-vue#367]
(using 2.0.10)

I have changed default template for f7-vue. In `form.vue` I changed the slider into

```
<f7-range min="0" max="100" value="50" step="1" :label="true" @change="alert('change');" @click="alert('click');"></f7-range>
```
I can see in the vue developer plugin of chrome that the event is fired, but no alert is shown

**Comment by nolimits4web** [comment]
There is no `change` event in range component http://framework7.io/vue/range-slider.html#range-slider-events it must be `@range:change="..."`

**Comment by nolimits4web** [comment]
And there is no `click` event on range. You may use native click event then as `@click.native="..."`

**Comment by lrbalt** [comment]
I have changed the line into
```
<f7-range min="0" max="100" value="50" step="1" :label="true" @range:change="onRange"></f7-range>
```

and added 
```
<script>
export default {
  methods: {
    onRange() {
      console.log("bla");
    }
  }
}
</script>
```

This works on Chromium, i.e. the console shows `bla` on changing the range. But on firefox, the range does not work. I cannot change the slider and it never calls `onRange`

Furthermore, when I use the range withing a f7-list-item as f7-input, the event is not fired:

```
<f7-list class="innerlist" inset>
   <f7-list-item>
      <f7-input class="source-volume" type="range" min="0" max="100" step="1" @range:change="onRange">/f7-input>
   </f7-list-item>
</f7-list>
```
