### ISSUE TITLE
set toggle checked 

### ISSUE THREAD

**Issue by 7aduta** [framework7io/framework7-vue#368]
i want to set the toggle value is checked programmatically

i tried to do
`this.$f7.toggle.get('toggle');`

but i get undefined

**Comment by nolimits4web** [comment]
.get(‘.toggle’)

**Comment by 7aduta** [comment]
sorry it was a typo  
thats what i did already 
`console.log(this.$f7.toggle.get('.toggle'))`

**Comment by kevinqqnj** [comment]
use Vue bind "checked" value with one variable.

`<f7-toggle :checked="manual_active" @change="manual_active = $event.target.checked" />`
