### ISSUE TITLE
[Vue warn]: Invalid handler for event "href": got undefined on Floating Action Button

### ISSUE THREAD

**Issue by droppy2014** [framework7io/framework7-vue#369]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10
* Framework7-Vue Version: 2.0.10
* Vue version 2.5.13
* Platform and Target: caiobiodere/cordova-template-framework7-vue-webpack

### What you did
After upgrading from Framework 2.0.7 to 2.0.10 there is in error after insert Floating Action Button block
```
<f7-fab color="pink" right-bottom class="fabfab">
<f7-link popup-open="#map_add"><f7-icon f7="+" size="25"></f7-icon></f7-link>
</f7-fab>
```
There is error

[Vue warn]: Invalid handler for event "href": got undefined

found in

---> <F7Fab>
       <F7Page>
         <Maps> at C:\meteor\geos\src\assets\vue\pages\maps.vue
           <F7View>
             <App> at C:\meteor\geos\src\main.vue
               <Root>
warn @ vue.common.js:580
updateListeners @ vue.common.js:2025
updateDOMListeners @ vue.common.js:6995
patchVnode @ vue.common.js:5835
updateChildren @ vue.common.js:5726
patchVnode @ vue.common.js:5840
patch @ vue.common.js:6000
Vue._update @ vue.common.js:2647
updateComponent @ vue.common.js:2765
get @ vue.common.js:3115
run @ vue.common.js:3192
flushSchedulerQueue @ vue.common.js:2954
(anonymous) @ vue.common.js:1813
flushCallbacks @ vue.common.js:1734
Promise.then (async)
microTimerFunc @ vue.common.js:1782
nextTick @ vue.common.js:1826
queueWatcher @ vue.common.js:3041
update @ vue.common.js:3182
notify @ vue.common.js:686
reactiveSetter @ vue.common.js:1011
proxySetter @ vue.common.js:3273
(anonymous) @ maps.vue?./node_modules/vue-loader/lib/selector.js?type=script&index=0:179
callbackFromNative @ cordova.js:294
(anonymous) @ VM2802:1
vue.common.js:580 [Vue warn]: Error in nextTick: "TypeError: Cannot read property '_withTask' of undefined"
warn @ vue.common.js:580
logError @ vue.common.js:1713
globalHandleError @ vue.common.js:1708
handleError @ vue.common.js:1697
(anonymous) @ vue.common.js:1815
flushCallbacks @ vue.common.js:1734
Promise.then (async)
microTimerFunc @ vue.common.js:1782
nextTick @ vue.common.js:1826
queueWatcher @ vue.common.js:3041
update @ vue.common.js:3182
notify @ vue.common.js:686
reactiveSetter @ vue.common.js:1011
proxySetter @ vue.common.js:3273
(anonymous) @ maps.vue?./node_modules/vue-loader/lib/selector.js?type=script&index=0:179
callbackFromNative @ cordova.js:294
(anonymous) @ VM2802:1
vue.common.js:1717 TypeError: Cannot read property '_withTask' of undefined
    at remove$2 (vue.common.js:6982)
    at updateListeners (vue.common.js:2042)
    at Array.updateDOMListeners (vue.common.js:6995)
    at patchVnode (vue.common.js:5835)
    at updateChildren (vue.common.js:5726)
    at patchVnode (vue.common.js:5840)
    at VueComponent.patch [as __patch__] (vue.common.js:6000)
    at VueComponent.Vue._update (vue.common.js:2647)
    at VueComponent.updateComponent (vue.common.js:2765)
    at Watcher.get (vue.common.js:3115)

### Expected Behavior
Floating Tab should open modal.

### Actual Behavior
There was not such error in 2.0.7. version and no code changed after upgrade.

**Comment by droppy2014** [comment]
I got it in changelog of 2.0.10
"Added href prop for f7-fab to set href attribute on main fab link"
So, it is needed to add href to fab, even if it is not used. I added href="#" and it worked.
```
<f7-fab color="pink" right-bottom class="fabfab" popup-open="#map_add" href="#">
<f7-icon f7="+" size="25"></f7-icon>
</f7-fab>
```

**Comment by nolimits4web** [comment]
Yes, there is an issue with it which is already fixed in src files, will be available in next release
