### ISSUE TITLE
f7-input clear-button not working

### ISSUE THREAD

**Issue by wenjiamian** [framework7io/framework7-vue#371]
This code:
<f7-input type="text" clear-button :value="budget" @input="budget = $event.target.value"></f7-input>

But 'clear-button' not working ，'budget' stay filled with old values
What should I do？

**Comment by nolimits4web** [comment]
Can you please provide a fiddle with the issue?

**Comment by almazk** [comment]
Try this 
`@change="budget = $event.target.value"`
, it should work.

**Comment by wenjiamian** [comment]
@nolimits4web @almazk Thanks, I tried this @change="budget = $event.target.value", it work.
