### ISSUE TITLE
Smart-Select after bind duplicates selected text label

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7-vue#373]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.7
* Framework7-Vue Version: 2.0.10
* Platform and Target: Web
* Live Link or JSFiddle: https://jsfiddle.net/qtsf8tr0/6/ (USE ABOUT PAGE)

### What you did
I created a smart-select with async items received by ajax (setTimeout in the fiddle above).
Set the current smart-select value doesn't display the selected text (the recommended way to do this is to bind f7-list `after` prop to this text).
In the documentation is also written that smart-select will use an existing `.item-after` div, if one exists.

### Expected Behavior
Show an async selected value and be able to change it:

![image](https://user-images.githubusercontent.com/379339/36876628-a6300c7c-1d94-11e8-8c09-e12c7a37dc28.png)

### Actual Behavior
When you select another option, the bound `after` prop remains (so the smart select now have two `.item-after`)

![image](https://user-images.githubusercontent.com/379339/36876644-b7e11eac-1d94-11e8-9268-f9b8d33d1a3d.png)

I guess vue smart-select is failing to identify and apply a pre-existing `.item-after` div, thus, duplicating it.

**Comment by nolimits4web** [comment]
Yeah, it is better to use SS api to update value here https://jsfiddle.net/z2w60ntk/
