### ISSUE TITLE
Inconsistencies among browsers on page-content padding when toolbar is in

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7-vue#374]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.7
* Framework7-Vue Version: 2.0.10
* Platform and Target: Browsers (both mobile and desktop) and IE

### What you did
I've created the following template: (the form encapsulates all tabs because I want the form changed event so I can persist my vue-model to localStorage (I need my model, not only the form)):

```
<template>
    <f7-page name="talents-curiculums-create" :page-content="false">
        <form id="curriculumForm" class="form-store-data extra-bottom-margin" style="height:100%;" @form:storedata="storeData">
            <f7-tabs animated>
                <f7-tab id="tab0" class="page-content">

...

                </f7-tab>
            </f7-tabs>
        </form>

        <f7-toolbar>
            <select class="jumpList" v-model="selectedTab">
                <option value="0" :selected="selectedTab === 0">Introdução</option>
...
            </select>
        </f7-toolbar>
    </f7-page>
</template>
```

### Expected Behavior
Chrome behavior:
![image](https://user-images.githubusercontent.com/379339/36880636-8548ff28-1da8-11e8-8c9a-489b9f8b5c88.png)

### Actual Behavior
FireFox Quantum, Edge and Internet Exploder 11:
![image](https://user-images.githubusercontent.com/379339/36880659-ad9bf9ee-1da8-11e8-8135-01dbb67dfcbf.png)

BUG: the bottom padding when a page has a toolbar on ios theme just works on Chrome.
I assume that works as well on mobile and Safari, but I'm not sure (and, yes, I know it was not supposed to work in non mobile browsers but, I just glad it does 99.9% perfectly)

**Comment by nolimits4web** [comment]
Yeah, it is a browser's issue with padding on `overflow: auto` containers. Check the simplest fiddle https://jsfiddle.net/Lcuje10p/

But, as the main target of F7 is Safari(webkit) and Chrome(blink) where it is working as it is expected, we are fine with it. Otherwise, some hacks must be added

**Comment by nolimits4web** [comment]
As a workaround for such browsers only this can be added:
```
.page-content:after{
  content: '';
  height: 48px; /* required padding bottom */
  display: block;
  width: 1px;
}
