### ISSUE TITLE
back-link="Back" not working, this.$f7router.history have only one item

### ISSUE THREAD

**Issue by ralbear** [framework7io/framework7-vue#375]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version:  "framework7": "^2.0.10",
* Framework7-Vue Version: "framework7-vue": "^2.0.10",
* Platform and Target: Chrome
* Live Link or JSFiddle: 

### What you did
I have a problem going back from the tipical about page to the main one with the standar `back-link=""` action
```
<f7-navbar title="Action Sheet" back-link="Back"></f7-navbar>
```
So i change that with this to make some test.
```
<div class="navbar-inner">
  <div class="left">
    <a href="#" class="link icon-only" @click="handle_back($event)">Back</a>
  </div>
</div>
```
```
methods: {
      handle_back(e) {
        console.log(this.$f7router)
},
```
### Expected Behavior
I make the same steps in other project where `back-link=""` works fine and i see this in `this.$f7router.history` for `Home -> About -> Login`
![image](https://user-images.githubusercontent.com/3120856/36910674-ad98c5be-1e41-11e8-90b0-08590847d03c.png)
In the Vue debuger tool for Chrome i get this events when i click in the `back-link=""` button
![image](https://user-images.githubusercontent.com/3120856/36911324-7da0772e-1e43-11e8-9c32-431d841449a0.png)

### Actual Behavior
But in the not working project i only get the last page in the history for `Home -> Test ->About`
![image](https://user-images.githubusercontent.com/3120856/36910787-fad47012-1e41-11e8-9e56-a9cdf429de53.png)
Also in the Vue debuger tool for Chrome i get this events when i click in the `back-link=""` button
![image](https://user-images.githubusercontent.com/3120856/36911299-685914d4-1e43-11e8-8dcc-9a46bb9ee5d6.png)

**Comment by nolimits4web** [comment]
I see you are using v1, not the v2. There is no such events on v1

**Comment by nolimits4web** [comment]
Explain in details what you are doing and what are you trying to achieve?

**Comment by ralbear** [comment]
Finally i reinstall a fresh project and move all the components because is a very small project and this issue takes me a lot of time and didn't find the solution. Thanks
