### ISSUE TITLE
[navbar]bg-color can not change background color by ios theme

### ISSUE THREAD

**Issue by owey0312** [framework7io/framework7-vue#382]
hi, 
    why i can not change bg-color of navbar in ios theme, but when i change theme to mat, i can do it.
    i use the vue template, some code i added as below.
     <f7-page>
    <f7-navbar bg-color="pink">
      <f7-nav-left>
        <f7-link icon-if-ios="f7:menu" icon-if-md="material:menu" panel-open="left" color="green"></f7-link>
      </f7-nav-left>
      <f7-nav-title text-color="black">My App111</f7-nav-title>
      <f7-nav-right>
        <f7-link  icon-if-ios="f7:menu" icon-if-md="material:menu" panel-open="right"></f7-link>
      </f7-nav-right>
    </f7-navbar>
      ...

![ios](https://user-images.githubusercontent.com/32464691/37339290-2d62777a-26f5-11e8-9a45-dccbb395bf8d.png)
![mat](https://user-images.githubusercontent.com/32464691/37339291-2da49f2e-26f5-11e8-9a1a-90f4efae5d9f.png)

**Comment by nolimits4web** [comment]
https://github.com/framework7io/framework7-vue/issues/333
