### ISSUE TITLE
Routing problem in v2

### ISSUE THREAD

**Issue by abhineshjdaas** [framework7io/framework7-vue#385]
I'm creating an app using framework7 v2. Previously i've worked with v1 and its good. v2 seems to be a major change from v1.

so i'm facing some problem in routing.. could u please help me..
currently, i'm using this version :
* Framework7 Version: 2.0.7.
* Framework7-Vue Version: 2.0.7.

InitApp using 
     routes: Routes,
      view: {
        pushState: true
      },

and route is 
 {
    path: '/test-view/:Id',
    component: Text
  },
 {
    path: '/another-view/:Id',
    component: Another
  },

when I navigate to test-view URL like this http://localhost:8080/#!/text-view/10930
this is fine for me.

the issue is when I try to navigate another view in text-view 
then URL shows 
http://localhost:8080/#!/text-view/10930/another-view/10940
this is the issue because doesn't find any router.

navigation link for both views is : 
<a href="text-view/10930" class="link" >
<a  href="another-view/10940" class="link" >

Please help me..

**Comment by nolimits4web** [comment]
Your href should start from `/`

**Comment by abhineshjdaas** [comment]
thanks it works 👍  
you are great @nolimits4web 👍
