### ISSUE TITLE
The ajax method  $request.post  work on Android  incorrect.

### ISSUE THREAD

**Issue by yaojunWang** [framework7io/framework7-vue#387]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.6.
* Framework7-Vue Version: 2.0.0.
* Platform and Target:  Android 6.0  Android 7.0  iOS 11.2.6.

### What I did

`/*a base64 encoded jpeg image.*/`
`var img ='XXXXXXXX';`
`var param = {};`
`param.contentBase64=encodeURIComponent(img);`
`app.$request.post(`
`    /* url */`
`    'http://stbs.market.alicloudapi.com/word/entity/recognize',`
`    /* data */`
`    param,`
`    /* success */`
`    function (data) {`
`        if(data.success){`
`            alert(data.data[0].contents)`
`        }else{`
`            console.log(data);`
`        }`
`    },`
`    /* error */`
`    function(err){`
`        console.log(err)`
`    },`
`    /* dataType */`
`    'json');`

### Expected Behavior
It works correctly on all platform.
### Actual Behavior
It works correctly on iOS to show the result json's contents,  but call  error callback on Android6.0 and Android 7.0. 

The error callback object like this:
![img_20180319_164507](https://user-images.githubusercontent.com/3361161/37585812-4e7951b4-2b95-11e8-835d-2df78cbcfa9b.png)

**Comment by nolimits4web** [comment]
1. Update F7 libs to latest
2. Check the console with request data, it works the same, but looks like there is a request error in Android that need to be checked in debug console

**Comment by yaojunWang** [comment]
@nolimits4web Thanks for advice.I updated the libs to 2.0.10 , but still not working. Is there any limit to the length of the parameter?

**Comment by nolimits4web** [comment]
Do other POST requests work in your Android app? You need to check debug console to see what is the issu

**Comment by yaojunWang** [comment]
Thanks.I find the answer [here](https://stackoverflow.com/questions/30060534/ajax-requests-fail-after-upgrading-to-cordova-5-0-cordova-android4-0)
