### ISSUE TITLE
Redirect with pushState and history

### ISSUE THREAD

**Issue by Jovaage** [framework7io/framework7-vue#388]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10.
* Framework7-Vue Version: 2.0.10.
* Platform and Target: Currently the chrome browser only.
* Repo showing the error: https://github.com/Jovaage/framework7-history-navigation-router-issue

### What you did
I added a fallback route that would redirect to another route
```js
// F7 options
framework7: {
    ...
    view: {
        history: true,
        pushState: true,
        pushStateSeparator: '',
    },
}

// The main route
{
    ...
    path: '/main/',
    options: {
        reloadCurrent: true,
    },
}

// The fallback route
{
    path: '(.*)',

    redirect: (route, resolve) => {
        resolve('/main/');
    },
}
```

### Expected Behavior
The state should be replaced to '/main/' when being redirected from the fallback route.

### Actual Behavior
Instead the view changes, and the internal routing is done, but the url in the address bar is still the same.

**Comment by nolimits4web** [comment]
I see everything works correctly in Kitchen sink and in your repo. You go to category page, you will have `/booking/category/`, then i write in console `app.$f7.views.main.router.navigate('/test/')` and it redirects me to `/booking/` page, and i see same `/booking/` in browser url

**Comment by Jovaage** [comment]
I see that I wasn't very clear.
This happens when you write an invalid url in the address bar.
Using `router.navigate`, like you said, works fine, but it seems to skip the `replaceState` call when you load the app into the invalid url.
