### ISSUE TITLE
Problem with "build": Unexpected token: name (Dom7)

### ISSUE THREAD

**Issue by caiotarifa** [framework7io/framework7-vue#393]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.1.3..
* Framework7-Vue Version: 2.1.2.
* Platform and Target: browser.

I am getting this error when I run `npm run build`.

![captura de tela 2018-03-23 as 13 12 08](https://user-images.githubusercontent.com/197979/37840594-49f48eb0-2e9c-11e8-8d89-168a7d713752.png)

```
ERROR in build.js from UglifyJs
Unexpected token: name (Dom7) [./node_modules/dom7/dist/dom7.module.js:16,0][build.js:666,6]
```

**Comment by nolimits4web** [comment]
If you use ESModule then you should configure babel https://github.com/framework7io/framework7-template-vue-webpack/blob/master/build/webpack.base.conf.js#L46-L49

**Comment by caiotarifa** [comment]
I did it but the problem persists.

Apparently it is not in the build process but in the compress process (UglifyJS).
