### ISSUE TITLE
Template is not working on device (phone)

### ISSUE THREAD

**Issue by yusufguleryuz** [framework7io/framework7-vue#395]
Project url: https://github.com/framework7io/framework7-template-vue-simple
Hi, i downloaded all files after build at build.phonegap.com. Then i installed that apk but not working vue template.... i think device can not compile vue template file.

P.s: All files are working localhost, or web but not working at device(apk --->phone).

What can i do?

**Comment by nolimits4web** [comment]
Does it work for you when you open it from browser https://framework7io.github.io/framework7-template-vue-simple/ ?

**Comment by nolimits4web** [comment]
This template doesn't use any files compilation, this is why it is called "Simple". Make sure you have followed the guide correctly https://github.com/framework7io/framework7-template-vue-simple#usage
