### ISSUE TITLE
Range sliders doesn't work in Panels

### ISSUE THREAD

**Issue by Jovaage** [framework7io/framework7-vue#396]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: latest.
* Framework7-Vue Version: latest.
* Platform and Target: Every.
* Live Link or JSFiddle: https://jsfiddle.net/k7tj0yfy/1/

### What you did
I put a range slider in a panel

### Expected Behavior
The slider should work

### Actual Behavior
The knob is stuck at 0, displaying `nan` when I press it.

I've found a somewhat [relevant forum post](http://forum.framework7.io/t/range-slider-in-dialog-does-not-work/1760/6), but it doesn't discuss how to fix it in vue.

**Comment by nolimits4web** [comment]
It was fixed in https://github.com/framework7io/framework7/commit/8725d94c9be73e180d8c7b4523642d55553d7df4 so will be with next F7 core update

**Comment by Jovaage** [comment]
When do you think this will be?

**Comment by nolimits4web** [comment]
End of the week or next week

**Comment by Jovaage** [comment]
Thank you

**Comment by nolimits4web** [comment]
You can manually call range’s “layout” and “calcSize” methods on panel open

**Comment by Jovaage** [comment]
How can I get access to those methods?
And where should I listen for `panel:open`?
Right now I've tried attaching to the page, inside the view, that inside the panel, but it doesn't seem to propagate downwards like that.
