### ISSUE TITLE
[v2] initial page not load in app

### ISSUE THREAD

**Issue by SiddiquiImran** [framework7io/framework7-vue#397]
I'm creating an app using framework7 v2. Previously I've worked with v1 and its good. v2 seems to be a major change from v1.

so I'm facing some problem in routing.. could u please help me.
currently, I'm using this version :

Framework7 Version: 2.0.7.
Framework7-Vue Version: 2.0.7.

InitApp using

```
routes: Routes,
view: {
pushState: true
},
```

and my route is
```
{
    path: '/',
    component: Home
},
{
   path: '/test-view/:Id',
   component: Test
},
```

app.vue code for view like

    <f7-view id="main-view" url="/" main></f7-view>

when I run in the web browser it works fine and shows home page.
but after build and create an APK and IPA using PhoneGap.

### Expected Behavior
It shows homepage initially.

### Actual Behavior
but currently, happen is the main view not render the home page, it shows the 404 page, means the route is not matched.

![image](https://user-images.githubusercontent.com/20870175/38140115-00296ddc-3450-11e8-9887-4a539826ad81.png)

I read this document also https://blog.framework7.io/mastering-v2-router-958ea2dbd24f
but not found any solution 

Please Help
Thanks In Advance.

**Comment by nolimits4web** [comment]
You need to configure `pushStateRoot` view's parameter correctly. Check forum there were plenty of similar topics

**Comment by SiddiquiImran** [comment]
Hi @nolimits4web 
please suggest any solution for this

**Comment by nolimits4web** [comment]
> can you please suggest what should be the value of pushStateRoot parameter

I believe it must be `/app/` when you run app on "http://my-webapp.com/app/"

**Comment by SiddiquiImran** [comment]
Thanks, It resolved 👍
