### ISSUE TITLE
infinite can not run in v2

### ISSUE THREAD

**Issue by cody-chen-jf** [framework7io/framework7-vue#398]
`<div class="page-content infinite-scroll" data-infinite-distance="30">`
`this.$$('.infinite-scroll').on('infinite', function () {})`

this can run in v1, but don't run in v2, Where do I need to change?

**Comment by nolimits4web** [comment]
http://framework7.io/docs/infinite-scroll.html#infinite-scroll-layout

**Comment by cody-chen-jf** [comment]
Thank you very much for your help. I solve the problem by modifying the **infinite-scroll** to **infinite-scroll-content**.
