### ISSUE TITLE
[v2] f7-messages showTyping

### ISSUE THREAD

**Issue by lislamov** [framework7io/framework7-vue#399]
Typing message indicator does not have 'message-last' class so avatar is not showing in this case

**Comment by nolimits4web** [comment]
Add `:last="true"` to typing indicator message https://github.com/framework7io/framework7-vue/blob/master/kitchen-sink/src/pages/messages.vue#L57-L65

**Comment by lislamov** [comment]
for v 2.2.0 and when I render (add/remove) typing message in declarative way
the
<div class="message-typing-indicator"><div></div><div></div><div></div></div>
is missing

**Comment by lislamov** [comment]
this div
`<div class="message-typing-indicator"><div></div><div></div><div></div></div>`

**Comment by nolimits4web** [comment]
It is there, if you also add `:typing="true"` like in example

**Comment by lislamov** [comment]
all like in example
`      <f7-message v-if="typingMessage"
        type="received"
        :typing="true"
        :first="true"
        :last="true"
        :tail="true"
        :header="`${typingMessage.name} is typing`"
        :avatar="typingMessage.avatar"
      ></f7-message>      
`
but in results
`<div data-v-39d6e5b4="" class="message message-received message-first message-last message-tail message-appear-from-bottom" typing="true"> <div class="message-avatar" style="background-image: url(&quot;https://staffconnect.net/images/nopic_thumb_female.jpg&quot;);"></div> <div class="message-content"> <!----> <div class="message-header">Admin3 Test is typing</div> <div class="message-bubble"> <!----> <!----> <!----> <!---->  </div> <!----> </div> </div>`

**Comment by nolimits4web** [comment]
You sure you have updated F7-Vue to latest?

**Comment by lislamov** [comment]
sorry for my inattention
I forgot restart webpack after packages update
thank you!
