### ISSUE TITLE
Auto-repeat (Tap & Hold) on Stepper component not working

### ISSUE THREAD

**Issue by jremi** [framework7io/framework7-vue#402]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.1.1
* Framework7-Vue Version: 2.2.0
* Platform and Target: iOS 11.x
* Live Link or JSFiddle: 
https://github.com/framework7io/framework7-vue/blob/master/kitchen-sink/src/pages/stepper.vue
Lines: 202-215

### What you did
Run the example on lines 202-215 of the live link.
### Expected Behavior
Pressing and holding one of its buttons increments or decrements the stepper’s value repeatedly.
### Actual Behavior
When I press and **hold** the - or + buttons it will does not decrement or increment.

**Comment by nolimits4web** [comment]
Update F7 lib to 2.2

**Comment by jremi** [comment]
@nolimits4web Thanks. Lib upgraded to 2.2 - Fixed 👍
