### ISSUE TITLE
Range Slider - draggableBar prop don´t work

### ISSUE THREAD

**Issue by Jaimet92** [framework7io/framework7-vue#404]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.1
* Framework7-Vue Version: 2.2.1
* Platform and Target: Android Cordova.

### What you did
`<f7-range
           min="1"
           max="100"
           step="1"
           draggableBar="false"
           disable="false"
           :value="getProgress"
       ></f7-range>`

### Expected Behavior
Range Slider don´t interact when swipe or click

### Actual Behavior
Range Slider interact when swipe or click

**Comment by nolimits4web** [comment]
Can't replicate it, works for me. Can you please provide a fiddle with the issue?

**Comment by Jaimet92** [comment]
https://jsfiddle.net/k7tj0yfy/13/

**Comment by nolimits4web** [comment]
This is weird, but as i see if you change it to `:draggable-bar` it will work as expected https://jsfiddle.net/v9nzbgzd/
