### ISSUE TITLE
Changing framework7 options on the go doesn't affect the app

### ISSUE THREAD

**Issue by iamabdeldayem** [framework7io/framework7-vue#418]
` Windows: 10 `
` npm: 5.6.0 `
` node: 8.11.1 `
` framework7: 2.0.6 `
` framework7-vue: 2.0.0 `
` webpack: 3.3.0 `

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
I want to change the layout from ` ltr ` to ` rtl `
__I've tried__
` this.$f7.rtl = true `
` this.$f7.init() `
__and also__
` this.$f7.params.rtl = true `
` this.$f7.init() `

Also when I pass ` rtl: true`  in ` new Framework7() ` options, nothing change.

When I change the style sheets from ` framework7.css ` to `frmaework7.rtl.css ` it works.
I want to change to rtl and ltr on the go.

### Expected Behavior
- Layout change from ` ltr ` to ` rtl `

### Actual Behavior
- Nothing changed, it suppose changed from ` ltr ` to `rtl ` layout.

I've checked this issue:
https://github.com/framework7io/framework7/issues/1389

but it doesn't help.

**Comment by nolimits4web** [comment]
It is by design and changing LTR to RTL is not supported on the fly, you have to change stylesheet and reinit the app
