### ISSUE TITLE
navbar back-link-url is ignored by f7-navbar

### ISSUE THREAD

**Issue by joebyrne** [framework7io/framework7-vue#427]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.1
* Framework7-Vue Version: 2.2.1.
* Platform and Target: testing in browser (chrome / windows).
* Live Link or JSFiddle: PREFERABLY https://jsfiddle.net/9csotp69/1/

### What you did
specified back-link-url on the f7-navbar in about page

### Expected Behavior
when visiting about page, and clicking back im expecting to be brought to the url specified

### Actual Behavior
The url is being ignored as there is a "back" property being set on the f7link which is being used.

When i manually add the nav bar using non vue component html structure, i dont add the "back" property / class and the page goes to the correct location... as i have done in the about 2 page in the jsfiddle.

The reason im doing this is .. i have implemented a method of serialising the state of the application, when the user logs back in they are brought to the exact page they were on previously, and application wont have any history ... when using the vue navbar component im always brought back to the login screen again, but should be brought "back" to the page specified in back-link-url

f7-link inside f7-nav has a "back" property always specified - prehaps this should only be added if backLinkUrl is not set?

<f7-link
      v-if="backLink"
      :href="backLinkUrl || '#'"
      back
      icon="icon-back"
      :class="{'icon-only': (backLink === true || backLink && $theme.md)}"
      :text="backLink !== true && !$theme.md ? backLink : undefined"
      @click="onBackClick"
      ></f7-link>

**Comment by joebyrne** [comment]
ok,  thanks,
For links in general, should force=true be the default when url is specified? why would someone specify a url and not want it to be used (why does the system ignore the url? unless force is true?) thanks, Joe

**Comment by nolimits4web** [comment]
> should force=true be the default when url is specified?

No, at least by design. By design it uses specified url only in case when there is no previous page in DOM

**Comment by jacobg** [comment]
Looks like the `back-link-force` prop needs to be added to docs.
