### ISSUE TITLE
List with inline labels and long text as link

### ISSUE THREAD

**Issue by lroal** [framework7io/framework7-vue#431]
I am trying to create a list with links, inline labels and a long text as content. The long text should have an ellipsis if it is too long. The long text should not be editable (just displayed in greyed as a link). I am having a hard time to do this. It might work if i override the styles - but suppose there is a cleaner way of doing it.

**Comment by lroal** [comment]
When adding this style, it works (copied from smart-select):   
```
.item-link .item-after {
  max-width: 70%;
  overflow: hidden;
  text-overflow: ellipsis;
  position: relative;
  display: block;
}
```
Maybe this should should be added to the f7 css. Or do you see any problem with that ?

**Comment by nolimits4web** [comment]
> Maybe this should should be added to the f7 css. Or do you see any problem with that ?

Yes, this styles are for some specific cases only, and can't be used globally. You shouldn't afraid of adding few custom styles, it is totally OK
