### ISSUE TITLE
f7-navbar 'no-hairline' and 'class' attributes not applying to element

### ISSUE THREAD

**Issue by rulrok** [framework7io/framework7-vue#435]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: from 2.2.5 to 2.3.1
* Framework7-Vue Version: from 2.2.5 to 2.3.0
* Platform and Target: Webbrowser (chrome)
* Live Link or JSFiddle: https://jsfiddle.net/te994sLq/1/

### What you did
I'm using the **f7-navbar** component but I can't set it to have no hairline

### Expected Behavior
Being able to both make the **no-hairline** property work and also the **class** property to replicate to the final rendered html.

### Actual Behavior
The **no-hairline** attribute has no effect on the component tag. Also, any class I try to apply through **class** attribute is not applied to the final html code.

**Comment by nolimits4web** [comment]
In iOS theme another common navbar is used, and it is created dynamically if there is no such. Just add empty navbar inside of View https://jsfiddle.net/oLb85saf/

**Comment by rulrok** [comment]
@nolimits4web That solved the problem! 
I must say it feels a little obscure. I didn't find this detail on the documentation.

Thank you.

**Comment by falstack** [comment]
but, i need set hairline use vue data, like this:
```
      :no-hairline="hiddenBorder"
      :no-shadow="hiddenBorder"
```

it not work on iOS

**Comment by rulrok** [comment]
@nolimits4web 
Hello again after some time.
As my team was finishing our app, we notices some memory leaks.

I could confirm that doing this trick causes a memory leak into my app.

What I have:

```html
<f7-view id="main-view" :main="true" :passRouteParamsToRequest="true">
        ...
</f7-view>
```
As soon as I add the empty navbar, the memory leaks starts happening:

```html
<f7-view id="main-view" :main="true" :passRouteParamsToRequest="true">
        <f7-navbar no-hairline></f7-navbar>
        ...
</f7-view>
```

Incredibly enough, Edge was helpful this time identifying the problem.

![image](https://user-images.githubusercontent.com/3097987/45178274-9af55380-b1eb-11e8-83e7-67a2913930ca.png)

I seems that f7page is holding a reference to navbar, which is in turn holding a reference do f7page, causing a circular dependency. Garbage collector cannot do its job.

The items with blue icons at the left mean that the element is detached from DOM
![image](https://user-images.githubusercontent.com/3097987/45178553-6a61e980-b1ec-11e8-8ba3-6a2502d3ef43.png)

**Comment by nolimits4web** [comment]
Should be removed now on pageBeforeRemove https://github.com/framework7io/framework7/commit/e3496b01147bd5fcfa766db653937b483eea6a50
