### ISSUE TITLE
Vue.use throws error, Framework7.device undefined

### ISSUE THREAD

**Issue by spiffytech** [framework7io/framework7-vue#437]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 3.0.0-beta.6
* Framework7-Vue Version: 3.0.0-beta.6
* Platform and Target: Cordova Android Oreo 8.1 in Android emulator
* Vue Version: 2.5.16

### What you did
I installed Framework7 and Framework7-Vue as specified in the docs:
```
$ npm install --save-dev framework7 framework7-vue
...
import Framework7 from 'framework7';
import Framework7Vue from 'framework7-vue';
import 'framework7/css/framework7.md.min.css';

Vue.use(Framework7Vue, Framework7);
```

### Expected Behavior
Framework7 initializes successfully

### Actual Behavior
`Vue.use` throws an error:
framework7-vue/utils/plugin.js:29
"Uncaught TypeError: Cannot read property 'ios' of undefined"

(That's in reference to the line `$theme.ios = !!(Framework7.Device || Framework7.device).ios;`)

**Comment by nolimits4web** [comment]
Use F7-Vue 2.x version for now. 3.x is still in beta and API has changed there

**Comment by owen-m1** [comment]
Same issue, on 3.1.1

**Comment by a-j-n** [comment]
same here

**Comment by nolimits4web** [comment]
1) This repository is deprecated!
2) Follow documentation http://framework7.io/vue/
