### ISSUE TITLE
[Request] Ability to set 'target' (_self, _blank, etc) on links and buttons

### ISSUE THREAD

**Issue by rulrok** [framework7io/framework7-vue#438]
This is a (multiple allowed):
* [  ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: current and up
* Framework7-Vue Version: current and up
* Platform and Target: I think this makes sense for browsers. I'm not sure about cordova.

### What you did
I set a `<f7-link>` with a `href` and `external` properties, but I needed it to allow me to set a `target` as well to overwrite the default '_self' which is used by the component.

### Expected Behavior
Use as 

`<f7-link external target="_blank" href="..."></f7-link>`

### Actual Behavior
It ignores the `target` attribute I set onto the component.

Thank you :smile:

**Comment by nolimits4web** [comment]
It is already supported https://jsfiddle.net/63xcg0wr/

**Comment by rulrok** [comment]
Hmmm.... interesting and weird. I was pretty sure to have tried this.
I will double check my code.

@nolimits4web JFYI In that case, the vue component documentation is missing that parameter.

Thanks again.

**Comment by rulrok** [comment]
@nolimits4web Hello again. I don't know what goes, but it randomly works.
Sometimes it creates the `target` property on the html element, and sometimes not.

One excerpt of my code:

```html
<f7-block inset strong>
      <f7-row v-for="(socialMediaChunk, index) of chunkedSocialMedias" :key="index" class="padding-bottom">
        <f7-col v-for="(socialMedia, index2) of socialMediaChunk" :key="index2">
          <f7-link :href="socialMedia[1]" external target="_blank" class="width-100">
            <component :is="socialMediaComponent(socialMedia[0])"></component>
          </f7-link>
        </f7-col>
      </f7-row>
    </f7-block>
```

It works at randomly. Any idea what could cause that?
