### ISSUE TITLE
v-model never updates for radio list items (f7-list-item)

### ISSUE THREAD

**Issue by infomaniac50** [framework7io/framework7-vue#99]
hasRadioModel is always false unless you set the undocumented property input-value. The kitchen sink example only shows usage of v-bind:value. 

Navigate to the Forms page and using the Vue developer tools you can see the hasRadioModel property does not equal true on the ListItem component.

I have not tested the checkbox list item but it may suffer from the same issue.

**Comment by joseph2002** [comment]
Use input-value for v-model is ok. Except that input-value can not be empty string.
from list-item.vue, valueComputed fallbacks to this.value if this.inputValue is empty.

**Comment by whipermr5** [comment]
+1. `v-model` for `f7-list-item` ought to be documented. Before reading this, I thought it was completely unimplemented - now I know that I just need to set the `input-value` property.

**Comment by ijry** [comment]
oh  这样啊

**Comment by ijry** [comment]
how to get f7-input switch's value? @joseph2002 @whipermr5 @macdonst @devgeeks

**Comment by whipermr5** [comment]
@ijry Do you mean for radio items? Like this:
```
<f7-list>
  <f7-list-item radio name="form_param" value="form_value_1" input-value="form_value_1" title="1st value" v-model="formParamValue"></f7-list-item>
  <f7-list-item radio name="form_param" value="form_value_2" input-value="form_value_1" title="2nd value" v-model="formParamValue"></f7-list-item>
  <f7-list-item radio name="form_param" value="form_value_3" input-value="form_value_1" title="3rd value" v-model="formParamValue"></f7-list-item>
</f7-list>
```

**Comment by kirin-yuen** [comment]
It works but I can't find input-value props on document.

**Comment by mix3d** [comment]
+1 for needing a docs update. Sorely lacking a "here's how you actually use this in Vue" bit.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
